<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/> <!--metatextblock--><title>Мегатрон
    3000</title>
    <meta property="og:url" content="megatron3000"/>
    <meta property="og:title" content="Мегатрон 3000"/>
    <meta property="og:description" content=""/>
    <meta property="og:type" content="website"/>
    <link rel="canonical" href="megatron"><!--/metatextblock-->
    <meta property="fb:app_id" content="257953674358265"/>
    <meta name="format-detection" content="telephone=no"/>
    <meta http-equiv="x-dns-prefetch-control" content="on">
    <link rel="shortcut icon" href="//ooosokol.ru/images/tildafavicon.ico" type="image/x-icon"/><!-- Assets -->
    <link rel="stylesheet" href="//ooosokol.ru/css/tilda-grid-3.0.min.css" type="text/css" media="all"/>
    <link rel="stylesheet" href="//ooosokol.ru/css/tilda-blocks-2.12.css?t=1596663071" type="text/css" media="all"/>
    <link rel="stylesheet" href="//ooosokol.ru/css/tilda-animation-1.0.min.css" type="text/css" media="all"/>
    <link rel="stylesheet" href="//ooosokol.ru/css/tilda-slds-1.4.min.css" type="text/css" media="all"/>
    <link rel="stylesheet" href="//ooosokol.ru/css/tilda-zoom-2.0.min.css" type="text/css" media="all"/>
    <script src="//ooosokol.ru/js/jquery-1.10.2.min.js"></script>
    <script src="//ooosokol.ru/js/tilda-scripts-2.8.min.js"></script>
    <script src="//ooosokol.ru/js/tilda-blocks-2.7.js?t=1596663071"></script>
    <script src="//ooosokol.ru/js/lazyload-1.3.min.js" charset="utf-8"></script>
    <script src="//ooosokol.ru/js/tilda-animation-1.0.min.js" charset="utf-8"></script>
    <script src="//ooosokol.ru/js/tilda-slds-1.4.min.js" charset="utf-8"></script>
    <script src="//ooosokol.ru/js/hammer.min.js" charset="utf-8"></script>
    <script src="//ooosokol.ru/js/tilda-zoom-2.0.min.js" charset="utf-8"></script>
    <script src="//ooosokol.ru/js/tilda-animation-sbs-1.0.min.js" charset="utf-8"></script>
    <script type="text/javascript">window.dataLayer = window.dataLayer || [];</script>
    <script type="text/javascript">if ((/bot|google|yandex|baidu|bing|msn|duckduckbot|teoma|slurp|crawler|spider|robot|crawling|facebook/i.test(navigator.userAgent)) === false && typeof (sessionStorage) != 'undefined' && sessionStorage.getItem('visited') !== 'y') {
            var style = document.createElement('style');
            style.type = 'text/css';
            style.innerHTML = '@media screen and (min-width: 980px) {.t-records {opacity: 0;}.t-records_animated {-webkit-transition: opacity ease-in-out .2s;-moz-transition: opacity ease-in-out .2s;-o-transition: opacity ease-in-out .2s;transition: opacity ease-in-out .2s;}.t-records.t-records_visible {opacity: 1;}}';
            document.getElementsByTagName('head')[0].appendChild(style);
            $(document).ready(function () {
                $('.t-records').addClass('t-records_animated');
                setTimeout(function () {
                    $('.t-records').addClass('t-records_visible');
                    sessionStorage.setItem('visited', 'y');
                }, 400);
            });
        }</script>
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript" >
        (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
            m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
        (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

        ym(66284041, "init", {
            clickmap:true,
            trackLinks:true,
            accurateTrackBounce:true,
            webvisor:true
        });
    </script>
    <noscript><div><img src="https://mc.yandex.ru/watch/66284041" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
</head>
<body class="t-body" style="margin:0;"><!--allrecords-->
<div id="allrecords" data-tilda-export="yes" class="t-records" data-hook="blocks-collection-content-node"
     data-tilda-project-id="2708073" data-tilda-page-id="12587013" data-tilda-page-alias="megatron3000"
     data-tilda-formskey="9d5a9705a3b96e8f725cb5ebb9b3a5dc">
    <div id="rec211441642" class="r t-rec" style=" " data-animationappear="off" data-record-type="396"><!-- T396 -->
        <style>#rec211441642 .t396__artboard {
                height: 365px;
                background-color: #ffffff;
            }

            #rec211441642 .t396__filter {
                height: 365px;
            }

            #rec211441642 .t396__carrier {
                height: 365px;
                background-position: center center;
                background-attachment: scroll;
                background-size: cover;
                background-repeat: no-repeat;
            }

            @media screen and (max-width: 1199px) {
                #rec211441642 .t396__artboard {
                    height: 375px;
                }

                #rec211441642 .t396__filter {
                    height: 375px;
                }

                #rec211441642 .t396__carrier {
                    height: 375px;
                    background-attachment: scroll;
                }
            }

            @media screen and (max-width: 959px) {
                #rec211441642 .t396__artboard {
                    height: 365px;
                }

                #rec211441642 .t396__filter {
                    height: 365px;
                }

                #rec211441642 .t396__carrier {
                    height: 365px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec211441642 .t396__artboard {
                    height: 265px;
                }

                #rec211441642 .t396__filter {
                    height: 265px;
                }

                #rec211441642 .t396__carrier {
                    height: 265px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec211441642 .t396__artboard {
                    height: 135px;
                }

                #rec211441642 .t396__filter {
                    height: 135px;
                }

                #rec211441642 .t396__carrier {
                    height: 135px;
                }
            }

            #rec211441642 .tn-elem[data-elem-id="1594126232344"] {
                z-index: 4;
                top: 38px;
                left: calc(50% - 600px + 229px);
                width: 747px;
            }

            #rec211441642 .tn-elem[data-elem-id="1594126232344"] .tn-atom {
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec211441642 .tn-elem[data-elem-id="1594126232344"] {
                    top: 50px;
                    left: calc(50% - 480px + 227px);
                    width: 507px;
                }
            }

            @media screen and (max-width: 959px) {
                #rec211441642 .tn-elem[data-elem-id="1594126232344"] {
                    top: 60px;
                    left: calc(50% - 320px + 151px);
                    width: 327px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec211441642 .tn-elem[data-elem-id="1594126232344"] {
                    top: 65px;
                    left: calc(50% - 240px + 110px);
                    width: 247px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec211441642 .tn-elem[data-elem-id="1594126232344"] {
                    top: 30px;
                    left: calc(50% - 160px + 90px);
                    width: 137px;
                }
            }

            #rec211441642 .tn-elem[data-elem-id="1594126244710"] {
                z-index: 3;
                top: 15px;
                left: calc(50% - 600px + 27px);
                width: 1146px;
                height: 164px;
            }

            #rec211441642 .tn-elem[data-elem-id="1594126244710"] .tn-atom {
                background-color: #00a551;
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec211441642 .tn-elem[data-elem-id="1594126244710"] {
                    top: 18px;
                    left: calc(50% - 480px + 21px);
                    width: 921px;
                    height: 164px;
                }
            }

            @media screen and (max-width: 959px) {
                #rec211441642 .tn-elem[data-elem-id="1594126244710"] {
                    top: 18px;
                    left: calc(50% - 320px + 27px);
                    width: 581px;
                    height: 125px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec211441642 .tn-elem[data-elem-id="1594126244710"] {
                    top: 18px;
                    left: calc(50% - 240px + 27px);
                    width: 427px;
                    height: 125px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec211441642 .tn-elem[data-elem-id="1594126244710"] {
                    top: 13px;
                    left: calc(50% - 160px + 20px);
                    width: 280px;
                    height: 60px;
                }
            }

            #rec211441642 .tn-elem[data-elem-id="1594126461002"] {
                z-index: 5;
                top: 45px;
                left: calc(50% - 600px + 1040px);
                width: 118px;
            }

            #rec211441642 .tn-elem[data-elem-id="1594126461002"] .tn-atom {
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec211441642 .tn-elem[data-elem-id="1594126461002"] {
                    top: 30px;
                    left: calc(50% - 480px + 790px);
                }
            }

            @media screen and (max-width: 959px) {
                #rec211441642 .tn-elem[data-elem-id="1594126461002"] {
                    top: 45px;
                    left: calc(50% - 320px + 500px);
                    width: 78px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec211441642 .tn-elem[data-elem-id="1594126461002"] {
                    top: 55px;
                    left: calc(50% - 240px + 380px);
                    width: 58px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec211441642 .tn-elem[data-elem-id="1594126461002"] {
                    top: 25px;
                    left: calc(50% - 160px + 240px);
                    width: 38px;
                }
            }

            #rec211441642 .tn-elem[data-elem-id="1594126492824"] {
                z-index: 6;
                top: 50px;
                left: calc(50% - 600px + 50px);
                width: 145px;
            }

            #rec211441642 .tn-elem[data-elem-id="1594126492824"] .tn-atom {
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
            }

            @media screen and (max-width: 959px) {
                #rec211441642 .tn-elem[data-elem-id="1594126492824"] {
                    top: 55px;
                    left: calc(50% - 320px + 40px);
                    width: 85px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec211441642 .tn-elem[data-elem-id="1594126492824"] {
                    top: 60px;
                    left: calc(50% - 240px + 40px);
                    width: 65px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec211441642 .tn-elem[data-elem-id="1594126492824"] {
                    top: 30px;
                    left: calc(50% - 160px + 30px);
                    width: 35px;
                }
            }

            #rec211441642 .tn-elem[data-elem-id="1594126564862"] {
                z-index: 2;
                top: 1px;
                left: calc(50% - 600px + 1px);
                width: 1198px;
                height: 364px;
            }

            #rec211441642 .tn-elem[data-elem-id="1594126564862"] .tn-atom {
                background-color: #40ffdd;
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec211441642 .tn-elem[data-elem-id="1594126564862"] {
                    top: 1px;
                    left: calc(50% - 480px + 2px);
                    width: 960px;
                    height: 373px;
                }
            }

            @media screen and (max-width: 959px) {
                #rec211441642 .tn-elem[data-elem-id="1594126564862"] {
                    top: 1px;
                    left: calc(50% - 320px + 0px);
                    width: 639px;
                    height: 366px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec211441642 .tn-elem[data-elem-id="1594126564862"] {
                    top: 1px;
                    left: calc(50% - 240px + 1px);
                    width: 478px;
                    height: 266px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec211441642 .tn-elem[data-elem-id="1594126564862"] {
                    top: 1px;
                    left: calc(50% - 160px + 0px);
                    width: 320px;
                    height: 142px;
                }
            }

            #rec211441642 .tn-elem[data-elem-id="1594127000761"] {
                z-index: 7;
                top: 225px;
                left: calc(50% - 600px + 40px);
                width: 349px;
            }

            #rec211441642 .tn-elem[data-elem-id="1594127000761"] .tn-atom {
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
            }

            @media screen and (max-width: 959px) {
                #rec211441642 .tn-elem[data-elem-id="1594127000761"] {
                    top: 180px;
                    left: calc(50% - 320px + 30px);
                    width: 159px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec211441642 .tn-elem[data-elem-id="1594127000761"] {
                    top: 179px;
                    left: calc(50% - 240px + 27px);
                    width: 109px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec211441642 .tn-elem[data-elem-id="1594127000761"] {
                    top: 90px;
                    left: calc(50% - 160px + 20px);
                    width: 69px;
                }
            }

            #rec211441642 .tn-elem[data-elem-id="1594127074891"] {
                z-index: 8;
                top: 210px;
                left: calc(50% - 600px + 420px);
                width: 150px;
            }

            #rec211441642 .tn-elem[data-elem-id="1594127074891"] .tn-atom {
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
            }

            @media screen and (max-width: 959px) {
                #rec211441642 .tn-elem[data-elem-id="1594127074891"] {
                    top: 210px;
                    left: calc(50% - 320px + 180px);
                    width: 70px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec211441642 .tn-elem[data-elem-id="1594127074891"] {
                    top: 175px;
                    left: calc(50% - 240px + 150px);
                }
            }

            @media screen and (max-width: 479px) {
                #rec211441642 .tn-elem[data-elem-id="1594127074891"] {
                    top: 91px;
                    left: calc(50% - 160px + 99px);
                    width: 40px;
                }
            }

            #rec211441642 .tn-elem[data-elem-id="1594141915746"] {
                z-index: 9;
                top: 220px;
                left: calc(50% - 600px + 810px);
                width: 325px;
            }

            #rec211441642 .tn-elem[data-elem-id="1594141915746"] .tn-atom {
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec211441642 .tn-elem[data-elem-id="1594141915746"] {
                    top: 255px;
                    left: calc(50% - 480px + 770px);
                    width: 145px;
                }
            }

            @media screen and (max-width: 959px) {
                #rec211441642 .tn-elem[data-elem-id="1594141915746"] {
                    top: 195px;
                    left: calc(50% - 320px + 420px);
                    width: 155px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec211441642 .tn-elem[data-elem-id="1594141915746"] {
                    top: 190px;
                    left: calc(50% - 240px + 370px);
                    width: 85px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec211441642 .tn-elem[data-elem-id="1594141915746"] {
                    top: 97px;
                    left: calc(50% - 160px + 219px);
                    width: 55px;
                }
            }

            #rec211441642 .tn-elem[data-elem-id="1594145394160"] {
                z-index: 11;
                top: 210px;
                left: calc(50% - 600px + 630px);
                width: 140px;
            }

            #rec211441642 .tn-elem[data-elem-id="1594145394160"] .tn-atom {
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec211441642 .tn-elem[data-elem-id="1594145394160"] {
                    top: 210px;
                    left: calc(50% - 480px + 620px);
                }
            }

            @media screen and (max-width: 959px) {
                #rec211441642 .tn-elem[data-elem-id="1594145394160"] {
                    top: 175px;
                    left: calc(50% - 320px + 300px);
                    width: 100px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec211441642 .tn-elem[data-elem-id="1594145394160"] {
                    top: 175px;
                    left: calc(50% - 240px + 300px);
                    width: 60px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec211441642 .tn-elem[data-elem-id="1594145394160"] {
                    top: 86px;
                    left: calc(50% - 160px + 165px);
                    width: 40px;
                }
            }

            #rec211441642 .tn-elem[data-elem-id="1594145536969"] {
                z-index: 12;
                top: 7px;
                left: calc(50% - 600px + 19px);
                width: 1162px;
                height: 2px;
            }

            #rec211441642 .tn-elem[data-elem-id="1594145536969"] .tn-atom {
                background-color: #ff0000;
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec211441642 .tn-elem[data-elem-id="1594145536969"] {
                    top: 7px;
                    left: calc(50% - 480px + 19px);
                    width: 927px;
                    height: 2px;
                }
            }

            @media screen and (max-width: 959px) {
                #rec211441642 .tn-elem[data-elem-id="1594145536969"] {
                    top: 7px;
                    left: calc(50% - 320px + 19px);
                    width: 598px;
                    height: 2px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec211441642 .tn-elem[data-elem-id="1594145536969"] {
                    top: 7px;
                    left: calc(50% - 240px + 19px);
                    width: 445px;
                    height: 2px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec211441642 .tn-elem[data-elem-id="1594145536969"] {
                    top: 7px;
                    left: calc(50% - 160px + 15px);
                    width: 291px;
                    height: 2px;
                }
            }

            #rec211441642 .tn-elem[data-elem-id="1594145691062"] {
                z-index: 14;
                top: 97px;
                left: calc(50% - 600px + -69px);
                width: 178px;
                height: 2px;
            }

            #rec211441642 .tn-elem[data-elem-id="1594145691062"] .tn-atom {
                -webkit-transform: rotate(90deg);
                -moz-transform: rotate(90deg);
                transform: rotate(90deg);
                background-color: #ff0000;
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
            }

            @media screen and (max-width: 959px) {
                #rec211441642 .tn-elem[data-elem-id="1594145691062"] {
                    top: 78px;
                    left: calc(50% - 320px + -52px);
                    width: 143px;
                    height: 2px;
                }
            }

            @media screen and (max-width: 639px) {
            }

            @media screen and (max-width: 479px) {
                #rec211441642 .tn-elem[data-elem-id="1594145691062"] {
                    top: 41px;
                    left: calc(50% - 160px + -21px);
                    width: 70px;
                    height: 2px;
                }
            }

            #rec211441642 .tn-elem[data-elem-id="1594145792453"] {
                z-index: 15;
                top: 196px;
                left: calc(50% - 600px + 20px);
                width: 560px;
                height: 3px;
            }

            #rec211441642 .tn-elem[data-elem-id="1594145792453"] .tn-atom {
                background-color: #907a8f;
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
            }

            @media screen and (max-width: 959px) {
                #rec211441642 .tn-elem[data-elem-id="1594145792453"] {
                    top: 163px;
                    left: calc(50% - 320px + 20px);
                    width: 256px;
                    height: 3px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec211441642 .tn-elem[data-elem-id="1594145792453"] {
                    top: 162px;
                    left: calc(50% - 240px + 17px);
                }
            }

            @media screen and (max-width: 479px) {
                #rec211441642 .tn-elem[data-elem-id="1594145792453"] {
                    top: 80px;
                    left: calc(50% - 160px + 14px);
                    width: 137px;
                    height: 2px;
                }
            }

            #rec211441642 .tn-elem[data-elem-id="1594145862309"] {
                z-index: 17;
                top: 277px;
                left: calc(50% - 600px + -60px);
                width: 162px;
                height: 4px;
            }

            #rec211441642 .tn-elem[data-elem-id="1594145862309"] .tn-atom {
                -webkit-transform: rotate(90deg);
                -moz-transform: rotate(90deg);
                transform: rotate(90deg);
                background-color: #907a8f;
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
            }

            @media screen and (max-width: 959px) {
                #rec211441642 .tn-elem[data-elem-id="1594145862309"] {
                    top: 224px;
                    left: calc(50% - 320px + -43px);
                    width: 126px;
                    height: 4px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec211441642 .tn-elem[data-elem-id="1594145862309"] {
                    top: 203px;
                    left: calc(50% - 240px + -26px);
                    width: 85px;
                    height: 4px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec211441642 .tn-elem[data-elem-id="1594145862309"] {
                    top: 105px;
                    left: calc(50% - 160px + -13px);
                    width: 52px;
                    height: 2px;
                }
            }

            #rec211441642 .tn-elem[data-elem-id="1594146462689"] {
                z-index: 21;
                top: 197px;
                left: calc(50% - 600px + 620px);
                width: 560px;
                height: 3px;
            }

            #rec211441642 .tn-elem[data-elem-id="1594146462689"] .tn-atom {
                background-color: #8400c3;
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec211441642 .tn-elem[data-elem-id="1594146462689"] {
                    top: 197px;
                    left: calc(50% - 480px + 610px);
                    width: 326px;
                    height: 3px;
                }
            }

            @media screen and (max-width: 959px) {
                #rec211441642 .tn-elem[data-elem-id="1594146462689"] {
                    top: 162px;
                    left: calc(50% - 320px + 290px);
                    width: 324px;
                    height: 3px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec211441642 .tn-elem[data-elem-id="1594146462689"] {
                    top: 162px;
                    left: calc(50% - 240px + 290px);
                    width: 173px;
                    height: 3px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec211441642 .tn-elem[data-elem-id="1594146462689"] {
                    top: 80px;
                    left: calc(50% - 160px + 159px);
                    width: 146px;
                    height: 2px;
                }
            }

            #rec211441642 .tn-elem[data-elem-id="1594391548607"] {
                z-index: 28;
                top: 97px;
                left: calc(50% - 600px + 1092px);
                width: 178px;
                height: 2px;
            }

            #rec211441642 .tn-elem[data-elem-id="1594391548607"] .tn-atom {
                -webkit-transform: rotate(90deg);
                -moz-transform: rotate(90deg);
                transform: rotate(90deg);
                background-color: #ff0000;
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec211441642 .tn-elem[data-elem-id="1594391548607"] {
                    top: 95px;
                    left: calc(50% - 480px + 856px);
                }
            }

            @media screen and (max-width: 959px) {
                #rec211441642 .tn-elem[data-elem-id="1594391548607"] {
                    top: 79px;
                    left: calc(50% - 320px + 544px);
                    width: 143px;
                    height: 2px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec211441642 .tn-elem[data-elem-id="1594391548607"] {
                    top: 78px;
                    left: calc(50% - 240px + 392px);
                }
            }

            @media screen and (max-width: 479px) {
                #rec211441642 .tn-elem[data-elem-id="1594391548607"] {
                    top: 41px;
                    left: calc(50% - 160px + 271px);
                    width: 70px;
                    height: 2px;
                }
            }

            #rec211441642 .tn-elem[data-elem-id="1594391557963"] {
                z-index: 29;
                top: 188px;
                left: calc(50% - 600px + 19px);
                width: 1162px;
                height: 2px;
            }

            #rec211441642 .tn-elem[data-elem-id="1594391557963"] .tn-atom {
                background-color: #ff0000;
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec211441642 .tn-elem[data-elem-id="1594391557963"] {
                    top: 185px;
                    left: calc(50% - 480px + 18px);
                    width: 927px;
                    height: 2px;
                }
            }

            @media screen and (max-width: 959px) {
                #rec211441642 .tn-elem[data-elem-id="1594391557963"] {
                    top: 150px;
                    left: calc(50% - 320px + 17px);
                    width: 598px;
                    height: 2px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec211441642 .tn-elem[data-elem-id="1594391557963"] {
                    top: 150px;
                    left: calc(50% - 240px + 18px);
                    width: 445px;
                    height: 2px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec211441642 .tn-elem[data-elem-id="1594391557963"] {
                    top: 75px;
                    left: calc(50% - 160px + 14px);
                    width: 291px;
                    height: 2px;
                }
            }

            #rec211441642 .tn-elem[data-elem-id="1594391629692"] {
                z-index: 30;
                top: 356px;
                left: calc(50% - 600px + 24px);
                width: 560px;
                height: 3px;
            }

            #rec211441642 .tn-elem[data-elem-id="1594391629692"] .tn-atom {
                background-color: #907a8f;
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec211441642 .tn-elem[data-elem-id="1594391629692"] {
                    top: 357px;
                    left: calc(50% - 480px + 21px);
                }
            }

            @media screen and (max-width: 959px) {
                #rec211441642 .tn-elem[data-elem-id="1594391629692"] {
                    top: 286px;
                    left: calc(50% - 320px + 19px);
                    width: 256px;
                    height: 3px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec211441642 .tn-elem[data-elem-id="1594391629692"] {
                    top: 246px;
                    left: calc(50% - 240px + 16px);
                }
            }

            @media screen and (max-width: 479px) {
                #rec211441642 .tn-elem[data-elem-id="1594391629692"] {
                    top: 130px;
                    left: calc(50% - 160px + 13px);
                    width: 137px;
                    height: 2px;
                }
            }

            #rec211441642 .tn-elem[data-elem-id="1594391642410"] {
                z-index: 31;
                top: 275px;
                left: calc(50% - 600px + 501px);
                width: 162px;
                height: 4px;
            }

            #rec211441642 .tn-elem[data-elem-id="1594391642410"] .tn-atom {
                -webkit-transform: rotate(90deg);
                -moz-transform: rotate(90deg);
                transform: rotate(90deg);
                background-color: #907a8f;
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec211441642 .tn-elem[data-elem-id="1594391642410"] {
                    top: 276px;
                    left: calc(50% - 480px + 500px);
                }
            }

            @media screen and (max-width: 959px) {
                #rec211441642 .tn-elem[data-elem-id="1594391642410"] {
                    top: 224px;
                    left: calc(50% - 320px + 213px);
                    width: 126px;
                    height: 4px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec211441642 .tn-elem[data-elem-id="1594391642410"] {
                    top: 203px;
                    left: calc(50% - 240px + 230px);
                    width: 85px;
                    height: 4px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec211441642 .tn-elem[data-elem-id="1594391642410"] {
                    top: 105px;
                    left: calc(50% - 160px + 124px);
                    width: 52px;
                    height: 2px;
                }
            }

            #rec211441642 .tn-elem[data-elem-id="1594146419037"] {
                z-index: 19;
                top: 277px;
                left: calc(50% - 600px + 538px);
                width: 164px;
                height: 4px;
            }

            #rec211441642 .tn-elem[data-elem-id="1594146419037"] .tn-atom {
                -webkit-transform: rotate(90deg);
                -moz-transform: rotate(90deg);
                transform: rotate(90deg);
                background-color: #8400c3;
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec211441642 .tn-elem[data-elem-id="1594146419037"] {
                    top: 277px;
                    left: calc(50% - 480px + 528px);
                }
            }

            @media screen and (max-width: 959px) {
                #rec211441642 .tn-elem[data-elem-id="1594146419037"] {
                    top: 224px;
                    left: calc(50% - 320px + 228px);
                    width: 125px;
                    height: 4px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec211441642 .tn-elem[data-elem-id="1594146419037"] {
                    top: 203px;
                    left: calc(50% - 240px + 246px);
                    width: 85px;
                    height: 4px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec211441642 .tn-elem[data-elem-id="1594146419037"] {
                    top: 105px;
                    left: calc(50% - 160px + 134px);
                    width: 51px;
                    height: 2px;
                }
            }

            #rec211441642 .tn-elem[data-elem-id="1594391797050"] {
                z-index: 32;
                top: 277px;
                left: calc(50% - 600px + 1097px);
                width: 164px;
                height: 4px;
            }

            #rec211441642 .tn-elem[data-elem-id="1594391797050"] .tn-atom {
                -webkit-transform: rotate(90deg);
                -moz-transform: rotate(90deg);
                transform: rotate(90deg);
                background-color: #8400c3;
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec211441642 .tn-elem[data-elem-id="1594391797050"] {
                    top: 277px;
                    left: calc(50% - 480px + 854px);
                }
            }

            @media screen and (max-width: 959px) {
                #rec211441642 .tn-elem[data-elem-id="1594391797050"] {
                    top: 222px;
                    left: calc(50% - 320px + 549px);
                    width: 125px;
                    height: 4px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec211441642 .tn-elem[data-elem-id="1594391797050"] {
                    top: 203px;
                    left: calc(50% - 240px + 421px);
                    width: 85px;
                    height: 4px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec211441642 .tn-elem[data-elem-id="1594391797050"] {
                    top: 105px;
                    left: calc(50% - 160px + 279px);
                    width: 51px;
                    height: 2px;
                }
            }

            #rec211441642 .tn-elem[data-elem-id="1594391816266"] {
                z-index: 33;
                top: 358px;
                left: calc(50% - 600px + 618px);
                width: 560px;
                height: 3px;
            }

            #rec211441642 .tn-elem[data-elem-id="1594391816266"] .tn-atom {
                background-color: #8400c3;
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec211441642 .tn-elem[data-elem-id="1594391816266"] {
                    top: 357px;
                    left: calc(50% - 480px + 611px);
                    width: 326px;
                    height: 3px;
                }
            }

            @media screen and (max-width: 959px) {
                #rec211441642 .tn-elem[data-elem-id="1594391816266"] {
                    top: 286px;
                    left: calc(50% - 320px + 289px);
                    width: 324px;
                    height: 3px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec211441642 .tn-elem[data-elem-id="1594391816266"] {
                    top: 244px;
                    left: calc(50% - 240px + 290px);
                    width: 173px;
                    height: 3px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec211441642 .tn-elem[data-elem-id="1594391816266"] {
                    top: 130px;
                    left: calc(50% - 160px + 159px);
                    width: 146px;
                    height: 2px;
                }
            }</style>
        <div class='t396'>
            <div class="t396__artboard" data-artboard-recid="211441642" data-artboard-height="365"
                 data-artboard-height-res-960="375" data-artboard-height-res-640="365"
                 data-artboard-height-res-480="265" data-artboard-height-res-320="135" data-artboard-height_vh=""
                 data-artboard-valign="center" data-artboard-ovrflw="">
                <div class="t396__carrier" data-artboard-recid="211441642"></div>
                <div class="t396__filter" data-artboard-recid="211441642"></div>
                <div class='t396__elem tn-elem tn-elem__2114416421594126232344' data-elem-id='1594126232344'
                     data-elem-type='image' data-field-top-value="38" data-field-top-res-960-value="50"
                     data-field-top-res-640-value="60" data-field-top-res-480-value="65"
                     data-field-top-res-320-value="30" data-field-left-value="229" data-field-left-res-960-value="227"
                     data-field-left-res-640-value="151" data-field-left-res-480-value="110"
                     data-field-left-res-320-value="90" data-field-width-value="747"
                     data-field-width-res-960-value="507" data-field-width-res-640-value="327"
                     data-field-width-res-480-value="247" data-field-width-res-320-value="137"
                     data-field-axisy-value="top" data-field-axisx-value="left" data-field-container-value="grid"
                     data-field-topunits-value="" data-field-leftunits-value="" data-field-heightunits-value=""
                     data-field-widthunits-value=""><a class='tn-atom' href="//ooosokol.ru/"> <img
                        class='tn-atom__img t-img'
                        data-original='//ooosokol.ru/images/tild6336-3233-4566-a136-623266383333__web_studio_sokol.png'
                        imgfield='tn_img_1594126232344'> </a></div>
                <div class='t396__elem tn-elem tn-elem__2114416421594126244710' data-elem-id='1594126244710'
                     data-elem-type='shape' data-field-top-value="15" data-field-top-res-960-value="18"
                     data-field-top-res-640-value="18" data-field-top-res-480-value="18"
                     data-field-top-res-320-value="13" data-field-left-value="27" data-field-left-res-960-value="21"
                     data-field-left-res-640-value="27" data-field-left-res-480-value="27"
                     data-field-left-res-320-value="20" data-field-height-value="164"
                     data-field-height-res-960-value="164" data-field-height-res-640-value="125"
                     data-field-height-res-480-value="125" data-field-height-res-320-value="60"
                     data-field-width-value="1146" data-field-width-res-960-value="921"
                     data-field-width-res-640-value="581" data-field-width-res-480-value="427"
                     data-field-width-res-320-value="280" data-field-axisy-value="top" data-field-axisx-value="left"
                     data-field-container-value="grid" data-field-topunits-value="" data-field-leftunits-value=""
                     data-field-heightunits-value="" data-field-widthunits-value="">
                    <div class='tn-atom'></div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2114416421594126461002' data-elem-id='1594126461002'
                     data-elem-type='image' data-field-top-value="45" data-field-top-res-960-value="30"
                     data-field-top-res-640-value="45" data-field-top-res-480-value="55"
                     data-field-top-res-320-value="25" data-field-left-value="1040" data-field-left-res-960-value="790"
                     data-field-left-res-640-value="500" data-field-left-res-480-value="380"
                     data-field-left-res-320-value="240" data-field-width-value="118"
                     data-field-width-res-640-value="78" data-field-width-res-480-value="58"
                     data-field-width-res-320-value="38" data-field-axisy-value="top" data-field-axisx-value="left"
                     data-field-container-value="grid" data-field-topunits-value="" data-field-leftunits-value=""
                     data-field-heightunits-value="" data-field-widthunits-value="">
                    <div class='tn-atom'><img class='tn-atom__img t-img'
                                              data-original='//ooosokol.ru/images/tild3461-3131-4639-b765-353265643930__mail_us.png'
                                              imgfield='tn_img_1594126461002'></div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2114416421594126492824' data-elem-id='1594126492824'
                     data-elem-type='image' data-field-top-value="50" data-field-top-res-640-value="55"
                     data-field-top-res-480-value="60" data-field-top-res-320-value="30" data-field-left-value="50"
                     data-field-left-res-640-value="40" data-field-left-res-480-value="40"
                     data-field-left-res-320-value="30" data-field-width-value="145" data-field-width-res-640-value="85"
                     data-field-width-res-480-value="65" data-field-width-res-320-value="35"
                     data-field-axisy-value="top" data-field-axisx-value="left" data-field-container-value="grid"
                     data-field-topunits-value="" data-field-leftunits-value="" data-field-heightunits-value=""
                     data-field-widthunits-value="" data-animate-sbs-event="click"
                     data-animate-sbs-trgels="1594126492824"
                     data-animate-sbs-opts="[{'ti':'0','mx':'0','my':'0','sx':'1','sy':'1','op':'1','ro':'0','bl':'0','ea':'','dt':'0'},{'ti':'1000','mx':'0','my':'0','sx':'1','sy':'1','op':'1','ro':'0','bl':'0','ea':'','dt':'0'}]">
                    <div class='tn-atom'><img class='tn-atom__img t-img'
                                              data-original='//ooosokol.ru/images/tild6432-3563-4630-a234-633035356238__burger.png'
                                              imgfield='tn_img_1594126492824'></div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2114416421594126564862' data-elem-id='1594126564862'
                     data-elem-type='shape' data-field-top-value="1" data-field-top-res-960-value="1"
                     data-field-top-res-640-value="1" data-field-top-res-480-value="1" data-field-top-res-320-value="1"
                     data-field-left-value="1" data-field-left-res-960-value="2" data-field-left-res-640-value="0"
                     data-field-left-res-480-value="1" data-field-left-res-320-value="0" data-field-height-value="364"
                     data-field-height-res-960-value="373" data-field-height-res-640-value="366"
                     data-field-height-res-480-value="266" data-field-height-res-320-value="142"
                     data-field-width-value="1198" data-field-width-res-960-value="960"
                     data-field-width-res-640-value="639" data-field-width-res-480-value="478"
                     data-field-width-res-320-value="320" data-field-axisy-value="top" data-field-axisx-value="left"
                     data-field-container-value="grid" data-field-topunits-value="" data-field-leftunits-value=""
                     data-field-heightunits-value="" data-field-widthunits-value="">
                    <div class='tn-atom'></div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2114416421594127000761' data-elem-id='1594127000761'
                     data-elem-type='image' data-field-top-value="225" data-field-top-res-640-value="180"
                     data-field-top-res-480-value="179" data-field-top-res-320-value="90" data-field-left-value="40"
                     data-field-left-res-640-value="30" data-field-left-res-480-value="27"
                     data-field-left-res-320-value="20" data-field-width-value="349"
                     data-field-width-res-640-value="159" data-field-width-res-480-value="109"
                     data-field-width-res-320-value="69" data-field-axisy-value="top" data-field-axisx-value="left"
                     data-field-container-value="grid" data-field-topunits-value="" data-field-leftunits-value=""
                     data-field-heightunits-value="" data-field-widthunits-value="">
                    <div class='tn-atom'><img class='tn-atom__img t-img'
                                              data-original='//ooosokol.ru/images/tild3737-6665-4933-b536-373830343438____.png'
                                              imgfield='tn_img_1594127000761'></div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2114416421594127074891' data-elem-id='1594127074891'
                     data-elem-type='image' data-field-top-value="210" data-field-top-res-640-value="210"
                     data-field-top-res-480-value="175" data-field-top-res-320-value="91" data-field-left-value="420"
                     data-field-left-res-640-value="180" data-field-left-res-480-value="150"
                     data-field-left-res-320-value="99" data-field-width-value="150" data-field-width-res-640-value="70"
                     data-field-width-res-320-value="40" data-field-axisy-value="top" data-field-axisx-value="left"
                     data-field-container-value="grid" data-field-topunits-value="" data-field-leftunits-value=""
                     data-field-heightunits-value="" data-field-widthunits-value="">
                    <div class='tn-atom'><img class='tn-atom__img t-img'
                                              data-original='//ooosokol.ru/images/tild3061-6532-4134-b334-646136326464__photo.png'
                                              imgfield='tn_img_1594127074891'></div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2114416421594141915746' data-elem-id='1594141915746'
                     data-elem-type='image' data-field-top-value="220" data-field-top-res-960-value="255"
                     data-field-top-res-640-value="195" data-field-top-res-480-value="190"
                     data-field-top-res-320-value="97" data-field-left-value="810" data-field-left-res-960-value="770"
                     data-field-left-res-640-value="420" data-field-left-res-480-value="370"
                     data-field-left-res-320-value="219" data-field-width-value="325"
                     data-field-width-res-960-value="145" data-field-width-res-640-value="155"
                     data-field-width-res-480-value="85" data-field-width-res-320-value="55"
                     data-field-axisy-value="top" data-field-axisx-value="left" data-field-container-value="grid"
                     data-field-topunits-value="" data-field-leftunits-value="" data-field-heightunits-value=""
                     data-field-widthunits-value="" data-animate-sbs-event="click"
                     data-animate-sbs-opts="[{'ti':'0','mx':'0','my':'0','sx':'1','sy':'1','op':'1','ro':'0','bl':'0','ea':'','dt':'0'}]">
                    <div class='tn-atom'><img class='tn-atom__img t-img'
                                              data-original='//ooosokol.ru/images/tild3536-3537-4035-b637-366339343730_________.png'
                                              imgfield='tn_img_1594141915746'></div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2114416421594145394160' data-elem-id='1594145394160'
                     data-elem-type='image' data-field-top-value="210" data-field-top-res-960-value="210"
                     data-field-top-res-640-value="175" data-field-top-res-480-value="175"
                     data-field-top-res-320-value="86" data-field-left-value="630" data-field-left-res-960-value="620"
                     data-field-left-res-640-value="300" data-field-left-res-480-value="300"
                     data-field-left-res-320-value="165" data-field-width-value="140"
                     data-field-width-res-640-value="100" data-field-width-res-480-value="60"
                     data-field-width-res-320-value="40" data-field-axisy-value="top" data-field-axisx-value="left"
                     data-field-container-value="grid" data-field-topunits-value="" data-field-leftunits-value=""
                     data-field-heightunits-value="" data-field-widthunits-value="">
                    <div class='tn-atom'><img class='tn-atom__img t-img'
                                              data-original='//ooosokol.ru/images/tild3434-6364-4739-b238-643734373161__cat.gif'
                                              imgfield='tn_img_1594145394160'></div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2114416421594145536969' data-elem-id='1594145536969'
                     data-elem-type='shape' data-field-top-value="7" data-field-top-res-960-value="7"
                     data-field-top-res-640-value="7" data-field-top-res-480-value="7" data-field-top-res-320-value="7"
                     data-field-left-value="19" data-field-left-res-960-value="19" data-field-left-res-640-value="19"
                     data-field-left-res-480-value="19" data-field-left-res-320-value="15" data-field-height-value="2"
                     data-field-height-res-960-value="2" data-field-height-res-640-value="2"
                     data-field-height-res-480-value="2" data-field-height-res-320-value="2"
                     data-field-width-value="1162" data-field-width-res-960-value="927"
                     data-field-width-res-640-value="598" data-field-width-res-480-value="445"
                     data-field-width-res-320-value="291" data-field-axisy-value="top" data-field-axisx-value="left"
                     data-field-container-value="grid" data-field-topunits-value="" data-field-leftunits-value=""
                     data-field-heightunits-value="" data-field-widthunits-value="">
                    <div class='tn-atom'></div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2114416421594145691062' data-elem-id='1594145691062'
                     data-elem-type='shape' data-field-top-value="97" data-field-top-res-640-value="78"
                     data-field-top-res-320-value="41" data-field-left-value="-69" data-field-left-res-640-value="-52"
                     data-field-left-res-320-value="-21" data-field-height-value="2" data-field-height-res-640-value="2"
                     data-field-height-res-320-value="2" data-field-width-value="178"
                     data-field-width-res-640-value="143" data-field-width-res-320-value="70"
                     data-field-axisy-value="top" data-field-axisx-value="left" data-field-container-value="grid"
                     data-field-topunits-value="" data-field-leftunits-value="" data-field-heightunits-value=""
                     data-field-widthunits-value="">
                    <div class='tn-atom'></div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2114416421594145792453' data-elem-id='1594145792453'
                     data-elem-type='shape' data-field-top-value="196" data-field-top-res-640-value="163"
                     data-field-top-res-480-value="162" data-field-top-res-320-value="80" data-field-left-value="20"
                     data-field-left-res-640-value="20" data-field-left-res-480-value="17"
                     data-field-left-res-320-value="14" data-field-height-value="3" data-field-height-res-640-value="3"
                     data-field-height-res-320-value="2" data-field-width-value="560"
                     data-field-width-res-640-value="256" data-field-width-res-320-value="137"
                     data-field-axisy-value="top" data-field-axisx-value="left" data-field-container-value="grid"
                     data-field-topunits-value="" data-field-leftunits-value="" data-field-heightunits-value=""
                     data-field-widthunits-value="">
                    <div class='tn-atom'></div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2114416421594145862309' data-elem-id='1594145862309'
                     data-elem-type='shape' data-field-top-value="277" data-field-top-res-640-value="224"
                     data-field-top-res-480-value="203" data-field-top-res-320-value="105" data-field-left-value="-60"
                     data-field-left-res-640-value="-43" data-field-left-res-480-value="-26"
                     data-field-left-res-320-value="-13" data-field-height-value="4" data-field-height-res-640-value="4"
                     data-field-height-res-480-value="4" data-field-height-res-320-value="2"
                     data-field-width-value="162" data-field-width-res-640-value="126"
                     data-field-width-res-480-value="85" data-field-width-res-320-value="52"
                     data-field-axisy-value="top" data-field-axisx-value="left" data-field-container-value="grid"
                     data-field-topunits-value="" data-field-leftunits-value="" data-field-heightunits-value=""
                     data-field-widthunits-value="">
                    <div class='tn-atom'></div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2114416421594146462689' data-elem-id='1594146462689'
                     data-elem-type='shape' data-field-top-value="197" data-field-top-res-960-value="197"
                     data-field-top-res-640-value="162" data-field-top-res-480-value="162"
                     data-field-top-res-320-value="80" data-field-left-value="620" data-field-left-res-960-value="610"
                     data-field-left-res-640-value="290" data-field-left-res-480-value="290"
                     data-field-left-res-320-value="159" data-field-height-value="3" data-field-height-res-960-value="3"
                     data-field-height-res-640-value="3" data-field-height-res-480-value="3"
                     data-field-height-res-320-value="2" data-field-width-value="560"
                     data-field-width-res-960-value="326" data-field-width-res-640-value="324"
                     data-field-width-res-480-value="173" data-field-width-res-320-value="146"
                     data-field-axisy-value="top" data-field-axisx-value="left" data-field-container-value="grid"
                     data-field-topunits-value="" data-field-leftunits-value="" data-field-heightunits-value=""
                     data-field-widthunits-value="">
                    <div class='tn-atom'></div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2114416421594391548607' data-elem-id='1594391548607'
                     data-elem-type='shape' data-field-top-value="97" data-field-top-res-960-value="95"
                     data-field-top-res-640-value="79" data-field-top-res-480-value="78"
                     data-field-top-res-320-value="41" data-field-left-value="1092" data-field-left-res-960-value="856"
                     data-field-left-res-640-value="544" data-field-left-res-480-value="392"
                     data-field-left-res-320-value="271" data-field-height-value="2" data-field-height-res-640-value="2"
                     data-field-height-res-320-value="2" data-field-width-value="178"
                     data-field-width-res-640-value="143" data-field-width-res-320-value="70"
                     data-field-axisy-value="top" data-field-axisx-value="left" data-field-container-value="grid"
                     data-field-topunits-value="" data-field-leftunits-value="" data-field-heightunits-value=""
                     data-field-widthunits-value="">
                    <div class='tn-atom'></div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2114416421594391557963' data-elem-id='1594391557963'
                     data-elem-type='shape' data-field-top-value="188" data-field-top-res-960-value="185"
                     data-field-top-res-640-value="150" data-field-top-res-480-value="150"
                     data-field-top-res-320-value="75" data-field-left-value="19" data-field-left-res-960-value="18"
                     data-field-left-res-640-value="17" data-field-left-res-480-value="18"
                     data-field-left-res-320-value="14" data-field-height-value="2" data-field-height-res-960-value="2"
                     data-field-height-res-640-value="2" data-field-height-res-480-value="2"
                     data-field-height-res-320-value="2" data-field-width-value="1162"
                     data-field-width-res-960-value="927" data-field-width-res-640-value="598"
                     data-field-width-res-480-value="445" data-field-width-res-320-value="291"
                     data-field-axisy-value="top" data-field-axisx-value="left" data-field-container-value="grid"
                     data-field-topunits-value="" data-field-leftunits-value="" data-field-heightunits-value=""
                     data-field-widthunits-value="">
                    <div class='tn-atom'></div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2114416421594391629692' data-elem-id='1594391629692'
                     data-elem-type='shape' data-field-top-value="356" data-field-top-res-960-value="357"
                     data-field-top-res-640-value="286" data-field-top-res-480-value="246"
                     data-field-top-res-320-value="130" data-field-left-value="24" data-field-left-res-960-value="21"
                     data-field-left-res-640-value="19" data-field-left-res-480-value="16"
                     data-field-left-res-320-value="13" data-field-height-value="3" data-field-height-res-640-value="3"
                     data-field-height-res-320-value="2" data-field-width-value="560"
                     data-field-width-res-640-value="256" data-field-width-res-320-value="137"
                     data-field-axisy-value="top" data-field-axisx-value="left" data-field-container-value="grid"
                     data-field-topunits-value="" data-field-leftunits-value="" data-field-heightunits-value=""
                     data-field-widthunits-value="">
                    <div class='tn-atom'></div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2114416421594391642410' data-elem-id='1594391642410'
                     data-elem-type='shape' data-field-top-value="275" data-field-top-res-960-value="276"
                     data-field-top-res-640-value="224" data-field-top-res-480-value="203"
                     data-field-top-res-320-value="105" data-field-left-value="501" data-field-left-res-960-value="500"
                     data-field-left-res-640-value="213" data-field-left-res-480-value="230"
                     data-field-left-res-320-value="124" data-field-height-value="4" data-field-height-res-640-value="4"
                     data-field-height-res-480-value="4" data-field-height-res-320-value="2"
                     data-field-width-value="162" data-field-width-res-640-value="126"
                     data-field-width-res-480-value="85" data-field-width-res-320-value="52"
                     data-field-axisy-value="top" data-field-axisx-value="left" data-field-container-value="grid"
                     data-field-topunits-value="" data-field-leftunits-value="" data-field-heightunits-value=""
                     data-field-widthunits-value="">
                    <div class='tn-atom'></div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2114416421594146419037' data-elem-id='1594146419037'
                     data-elem-type='shape' data-field-top-value="277" data-field-top-res-960-value="277"
                     data-field-top-res-640-value="224" data-field-top-res-480-value="203"
                     data-field-top-res-320-value="105" data-field-left-value="538" data-field-left-res-960-value="528"
                     data-field-left-res-640-value="228" data-field-left-res-480-value="246"
                     data-field-left-res-320-value="134" data-field-height-value="4" data-field-height-res-640-value="4"
                     data-field-height-res-480-value="4" data-field-height-res-320-value="2"
                     data-field-width-value="164" data-field-width-res-640-value="125"
                     data-field-width-res-480-value="85" data-field-width-res-320-value="51"
                     data-field-axisy-value="top" data-field-axisx-value="left" data-field-container-value="grid"
                     data-field-topunits-value="" data-field-leftunits-value="" data-field-heightunits-value=""
                     data-field-widthunits-value="">
                    <div class='tn-atom'></div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2114416421594391797050' data-elem-id='1594391797050'
                     data-elem-type='shape' data-field-top-value="277" data-field-top-res-960-value="277"
                     data-field-top-res-640-value="222" data-field-top-res-480-value="203"
                     data-field-top-res-320-value="105" data-field-left-value="1097" data-field-left-res-960-value="854"
                     data-field-left-res-640-value="549" data-field-left-res-480-value="421"
                     data-field-left-res-320-value="279" data-field-height-value="4" data-field-height-res-640-value="4"
                     data-field-height-res-480-value="4" data-field-height-res-320-value="2"
                     data-field-width-value="164" data-field-width-res-640-value="125"
                     data-field-width-res-480-value="85" data-field-width-res-320-value="51"
                     data-field-axisy-value="top" data-field-axisx-value="left" data-field-container-value="grid"
                     data-field-topunits-value="" data-field-leftunits-value="" data-field-heightunits-value=""
                     data-field-widthunits-value="">
                    <div class='tn-atom'></div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2114416421594391816266' data-elem-id='1594391816266'
                     data-elem-type='shape' data-field-top-value="358" data-field-top-res-960-value="357"
                     data-field-top-res-640-value="286" data-field-top-res-480-value="244"
                     data-field-top-res-320-value="130" data-field-left-value="618" data-field-left-res-960-value="611"
                     data-field-left-res-640-value="289" data-field-left-res-480-value="290"
                     data-field-left-res-320-value="159" data-field-height-value="3" data-field-height-res-960-value="3"
                     data-field-height-res-640-value="3" data-field-height-res-480-value="3"
                     data-field-height-res-320-value="2" data-field-width-value="560"
                     data-field-width-res-960-value="326" data-field-width-res-640-value="324"
                     data-field-width-res-480-value="173" data-field-width-res-320-value="146"
                     data-field-axisy-value="top" data-field-axisx-value="left" data-field-container-value="grid"
                     data-field-topunits-value="" data-field-leftunits-value="" data-field-heightunits-value=""
                     data-field-widthunits-value="">
                    <div class='tn-atom'></div>
                </div>
            </div>
        </div>
        <script>$(document).ready(function () {
                t396_init('211441642');
            });</script><!-- /T396 --></div>
    <div id="rec211441746" class="r t-rec" style=" " data-animationappear="off" data-record-type="396"><!-- T396 -->
        <style>#rec211441746 .t396__artboard {
                height: 70px;
                background-color: #ffffff;
            }

            #rec211441746 .t396__filter {
                height: 70px;
            }

            #rec211441746 .t396__carrier {
                height: 70px;
                background-position: center center;
                background-attachment: scroll;
                background-size: cover;
                background-repeat: no-repeat;
            }

            @media screen and (max-width: 1199px) {
                #rec211441746 .t396__artboard {
                }

                #rec211441746 .t396__filter {
                }

                #rec211441746 .t396__carrier {
                    background-attachment: scroll;
                }
            }

            @media screen and (max-width: 959px) {
            }

            @media screen and (max-width: 639px) {
            }

            @media screen and (max-width: 479px) {
                #rec211441746 .t396__artboard {
                    height: 70px;
                }

                #rec211441746 .t396__filter {
                    height: 70px;
                }

                #rec211441746 .t396__carrier {
                    height: 70px;
                }
            }

            #rec211441746 .tn-elem[data-elem-id="1594207705260"] {
                z-index: 2;
                top: 20px;
                left: calc(50% - 600px + 780px);
                width: 150px;
            }

            #rec211441746 .tn-elem[data-elem-id="1594207705260"] .tn-atom {
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec211441746 .tn-elem[data-elem-id="1594207705260"] {
                    top: 20px;
                    left: calc(50% - 480px + 650px);
                    width: 120px;
                }
            }

            @media screen and (max-width: 959px) {
                #rec211441746 .tn-elem[data-elem-id="1594207705260"] {
                    top: 25px;
                    left: calc(50% - 320px + 420px);
                    width: 90px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec211441746 .tn-elem[data-elem-id="1594207705260"] {
                    top: 44px;
                    left: calc(50% - 240px + 130px);
                    width: 90px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec211441746 .tn-elem[data-elem-id="1594207705260"] {
                    top: 40px;
                    left: calc(50% - 160px + 110px);
                    width: 90px;
                }
            }

            #rec211441746 .tn-elem[data-elem-id="1594207705269"] {
                z-index: 3;
                top: 20px;
                left: calc(50% - 600px + 590px);
                width: 150px;
            }

            #rec211441746 .tn-elem[data-elem-id="1594207705269"] .tn-atom {
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec211441746 .tn-elem[data-elem-id="1594207705269"] {
                    top: 20px;
                    left: calc(50% - 480px + 490px);
                    width: 120px;
                }
            }

            @media screen and (max-width: 959px) {
                #rec211441746 .tn-elem[data-elem-id="1594207705269"] {
                    top: 25px;
                    left: calc(50% - 320px + 320px);
                    width: 90px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec211441746 .tn-elem[data-elem-id="1594207705269"] {
                    top: 15px;
                    left: calc(50% - 240px + 330px);
                    width: 90px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec211441746 .tn-elem[data-elem-id="1594207705269"] {
                    top: 40px;
                    left: calc(50% - 160px + 10px);
                    width: 90px;
                }
            }

            #rec211441746 .tn-elem[data-elem-id="1594207705276"] {
                z-index: 4;
                top: 20px;
                left: calc(50% - 600px + 970px);
                width: 150px;
            }

            #rec211441746 .tn-elem[data-elem-id="1594207705276"] .tn-atom {
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec211441746 .tn-elem[data-elem-id="1594207705276"] {
                    top: 20px;
                    left: calc(50% - 480px + 810px);
                    width: 120px;
                }
            }

            @media screen and (max-width: 959px) {
                #rec211441746 .tn-elem[data-elem-id="1594207705276"] {
                    top: 25px;
                    left: calc(50% - 320px + 520px);
                    width: 90px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec211441746 .tn-elem[data-elem-id="1594207705276"] {
                    top: 44px;
                    left: calc(50% - 240px + 230px);
                    width: 90px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec211441746 .tn-elem[data-elem-id="1594207705276"] {
                    top: 40px;
                    left: calc(50% - 160px + 214px);
                    width: 90px;
                }
            }

            #rec211441746 .tn-elem[data-elem-id="1594207705283"] {
                z-index: 5;
                top: 20px;
                left: calc(50% - 600px + 220px);
                width: 150px;
            }

            #rec211441746 .tn-elem[data-elem-id="1594207705283"] .tn-atom {
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec211441746 .tn-elem[data-elem-id="1594207705283"] {
                    top: 20px;
                    left: calc(50% - 480px + 170px);
                    width: 120px;
                }
            }

            @media screen and (max-width: 959px) {
                #rec211441746 .tn-elem[data-elem-id="1594207705283"] {
                    top: 25px;
                    left: calc(50% - 320px + 120px);
                    width: 90px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec211441746 .tn-elem[data-elem-id="1594207705283"] {
                    top: 15px;
                    left: calc(50% - 240px + 130px);
                    width: 90px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec211441746 .tn-elem[data-elem-id="1594207705283"] {
                    top: 9px;
                    left: calc(50% - 160px + 110px);
                    width: 90px;
                }
            }

            #rec211441746 .tn-elem[data-elem-id="1594207705290"] {
                z-index: 6;
                top: 20px;
                left: calc(50% - 600px + 400px);
                width: 150px;
            }

            #rec211441746 .tn-elem[data-elem-id="1594207705290"] .tn-atom {
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec211441746 .tn-elem[data-elem-id="1594207705290"] {
                    top: 20px;
                    left: calc(50% - 480px + 330px);
                    width: 120px;
                }
            }

            @media screen and (max-width: 959px) {
                #rec211441746 .tn-elem[data-elem-id="1594207705290"] {
                    top: 25px;
                    left: calc(50% - 320px + 220px);
                    width: 90px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec211441746 .tn-elem[data-elem-id="1594207705290"] {
                    top: 15px;
                    left: calc(50% - 240px + 230px);
                    width: 90px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec211441746 .tn-elem[data-elem-id="1594207705290"] {
                    top: 9px;
                    left: calc(50% - 160px + 214px);
                    width: 90px;
                }
            }

            #rec211441746 .tn-elem[data-elem-id="1594207705299"] {
                z-index: 7;
                top: 20px;
                left: calc(50% - 600px + 40px);
                width: 150px;
            }

            #rec211441746 .tn-elem[data-elem-id="1594207705299"] .tn-atom {
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec211441746 .tn-elem[data-elem-id="1594207705299"] {
                    top: 20px;
                    left: calc(50% - 480px + 10px);
                    width: 120px;
                }
            }

            @media screen and (max-width: 959px) {
                #rec211441746 .tn-elem[data-elem-id="1594207705299"] {
                    top: 25px;
                    left: calc(50% - 320px + 20px);
                    width: 90px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec211441746 .tn-elem[data-elem-id="1594207705299"] {
                    top: 15px;
                    left: calc(50% - 240px + 20px);
                    width: 90px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec211441746 .tn-elem[data-elem-id="1594207705299"] {
                    top: 9px;
                    left: calc(50% - 160px + 10px);
                    width: 90px;
                }
            }

            #rec211441746 .tn-elem[data-elem-id="1594207741089"] {
                z-index: 1;
                top: 1px;
                left: calc(50% - 600px + 1px);
                width: 1198px;
                height: 69px;
            }

            #rec211441746 .tn-elem[data-elem-id="1594207741089"] .tn-atom {
                background-color: #ff0000;
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec211441746 .tn-elem[data-elem-id="1594207741089"] {
                    top: 1px;
                    left: calc(50% - 480px + -30px);
                    width: 1020px;
                    height: 69px;
                }
            }

            @media screen and (max-width: 959px) {
                #rec211441746 .tn-elem[data-elem-id="1594207741089"] {
                    top: 1px;
                    left: calc(50% - 320px + 1px);
                    width: 639px;
                    height: 69px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec211441746 .tn-elem[data-elem-id="1594207741089"] {
                    top: 1px;
                    left: calc(50% - 240px + 1px);
                    width: 478px;
                    height: 69px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec211441746 .tn-elem[data-elem-id="1594207741089"] {
                    top: 1px;
                    left: calc(50% - 160px + 1px);
                    width: 318px;
                    height: 69px;
                }
            }</style>
        <div class='t396'>
            <div class="t396__artboard" data-artboard-recid="211441746" data-artboard-height="70"
                 data-artboard-height-res-320="70" data-artboard-height_vh="" data-artboard-valign="center"
                 data-artboard-ovrflw="">
                <div class="t396__carrier" data-artboard-recid="211441746"></div>
                <div class="t396__filter" data-artboard-recid="211441746"></div>
                <div class='t396__elem tn-elem tn-elem__2114417461594207705260' data-elem-id='1594207705260'
                     data-elem-type='image' data-field-top-value="20" data-field-top-res-960-value="20"
                     data-field-top-res-640-value="25" data-field-top-res-480-value="44"
                     data-field-top-res-320-value="40" data-field-left-value="780" data-field-left-res-960-value="650"
                     data-field-left-res-640-value="420" data-field-left-res-480-value="130"
                     data-field-left-res-320-value="110" data-field-width-value="150"
                     data-field-width-res-960-value="120" data-field-width-res-640-value="90"
                     data-field-width-res-480-value="90" data-field-width-res-320-value="90"
                     data-field-axisy-value="top" data-field-axisx-value="left" data-field-container-value="grid"
                     data-field-topunits-value="" data-field-leftunits-value="" data-field-heightunits-value=""
                     data-field-widthunits-value=""><a class='tn-atom' href="//ooosokol.ru/contacts"> <img class='tn-atom__img t-img'
                                                                                             data-original='//ooosokol.ru/images/tild3231-6166-4034-a438-626166363865__button_kontakti.png'
                                                                                             imgfield='tn_img_1594207705260'>
                    </a></div>
                <div class='t396__elem tn-elem tn-elem__2114417461594207705269' data-elem-id='1594207705269'
                     data-elem-type='image' data-field-top-value="20" data-field-top-res-960-value="20"
                     data-field-top-res-640-value="25" data-field-top-res-480-value="15"
                     data-field-top-res-320-value="40" data-field-left-value="590" data-field-left-res-960-value="490"
                     data-field-left-res-640-value="320" data-field-left-res-480-value="330"
                     data-field-left-res-320-value="10" data-field-width-value="150"
                     data-field-width-res-960-value="120" data-field-width-res-640-value="90"
                     data-field-width-res-480-value="90" data-field-width-res-320-value="90"
                     data-field-axisy-value="top" data-field-axisx-value="left" data-field-container-value="grid"
                     data-field-topunits-value="" data-field-leftunits-value="" data-field-heightunits-value=""
                     data-field-widthunits-value=""><a class='tn-atom' href="//ooosokol.ru/office-interactive"> <img
                                class='tn-atom__img t-img'
                                data-original='//ooosokol.ru/images/tild3836-3264-4234-b730-393937333737__button_nash_office.png'
                                imgfield='tn_img_1594207705269'> </a></div>
                <div class='t396__elem tn-elem tn-elem__2114417461594207705276' data-elem-id='1594207705276'
                     data-elem-type='image' data-field-top-value="20" data-field-top-res-960-value="20"
                     data-field-top-res-640-value="25" data-field-top-res-480-value="44"
                     data-field-top-res-320-value="40" data-field-left-value="970" data-field-left-res-960-value="810"
                     data-field-left-res-640-value="520" data-field-left-res-480-value="230"
                     data-field-left-res-320-value="214" data-field-width-value="150"
                     data-field-width-res-960-value="120" data-field-width-res-640-value="90"
                     data-field-width-res-480-value="90" data-field-width-res-320-value="90"
                     data-field-axisy-value="top" data-field-axisx-value="left" data-field-container-value="grid"
                     data-field-topunits-value="" data-field-leftunits-value="" data-field-heightunits-value=""
                     data-field-widthunits-value=""><a class='tn-atom' href="//ooosokol.ru/otzivy"> <img class='tn-atom__img t-img'
                                                                                           data-original='//ooosokol.ru/images/tild6338-6439-4238-a437-326636303633__button_otzivi.png'
                                                                                           imgfield='tn_img_1594207705276'>
                    </a></div>
                <div class='t396__elem tn-elem tn-elem__2114417461594207705283' data-elem-id='1594207705283'
                     data-elem-type='image' data-field-top-value="20" data-field-top-res-960-value="20"
                     data-field-top-res-640-value="25" data-field-top-res-480-value="15"
                     data-field-top-res-320-value="9" data-field-left-value="220" data-field-left-res-960-value="170"
                     data-field-left-res-640-value="120" data-field-left-res-480-value="130"
                     data-field-left-res-320-value="110" data-field-width-value="150"
                     data-field-width-res-960-value="120" data-field-width-res-640-value="90"
                     data-field-width-res-480-value="90" data-field-width-res-320-value="90"
                     data-field-axisy-value="top" data-field-axisx-value="left" data-field-container-value="grid"
                     data-field-topunits-value="" data-field-leftunits-value="" data-field-heightunits-value=""
                     data-field-widthunits-value=""><a class='tn-atom' href="//ooosokol.ru/portfolio"> <img class='tn-atom__img t-img'
                                                                                              data-original='//ooosokol.ru/images/tild3662-3966-4532-b332-616330356633__button_portfolio.png'
                                                                                              imgfield='tn_img_1594207705283'>
                    </a></div>
                <div class='t396__elem tn-elem tn-elem__2114417461594207705290' data-elem-id='1594207705290'
                     data-elem-type='image' data-field-top-value="20" data-field-top-res-960-value="20"
                     data-field-top-res-640-value="25" data-field-top-res-480-value="15"
                     data-field-top-res-320-value="9" data-field-left-value="400" data-field-left-res-960-value="330"
                     data-field-left-res-640-value="220" data-field-left-res-480-value="230"
                     data-field-left-res-320-value="214" data-field-width-value="150"
                     data-field-width-res-960-value="120" data-field-width-res-640-value="90"
                     data-field-width-res-480-value="90" data-field-width-res-320-value="90"
                     data-field-axisy-value="top" data-field-axisx-value="left" data-field-container-value="grid"
                     data-field-topunits-value="" data-field-leftunits-value="" data-field-heightunits-value=""
                     data-field-widthunits-value=""><a class='tn-atom' href="//ooosokol.ru/pricelist"> <img class='tn-atom__img t-img'
                                                                                              data-original='//ooosokol.ru/images/tild6263-3061-4862-b763-346165386135__button_price_list.png'
                                                                                              imgfield='tn_img_1594207705290'>
                    </a></div>
                <div class='t396__elem tn-elem tn-elem__2114417461594207705299' data-elem-id='1594207705299'
                     data-elem-type='image' data-field-top-value="20" data-field-top-res-960-value="20"
                     data-field-top-res-640-value="25" data-field-top-res-480-value="15"
                     data-field-top-res-320-value="9" data-field-left-value="40" data-field-left-res-960-value="10"
                     data-field-left-res-640-value="20" data-field-left-res-480-value="20"
                     data-field-left-res-320-value="10" data-field-width-value="150"
                     data-field-width-res-960-value="120" data-field-width-res-640-value="90"
                     data-field-width-res-480-value="90" data-field-width-res-320-value="90"
                     data-field-axisy-value="top" data-field-axisx-value="left" data-field-container-value="grid"
                     data-field-topunits-value="" data-field-leftunits-value="" data-field-heightunits-value=""
                     data-field-widthunits-value=""><a class='tn-atom' href="//ooosokol.ru/uslugi"> <img class='tn-atom__img t-img'
                                                                                           data-original='//ooosokol.ru/images/tild3139-3038-4036-b731-386665316263__button_uslugi.png'
                                                                                           imgfield='tn_img_1594207705299'>
                    </a></div>
                <div class='t396__elem tn-elem tn-elem__2114417461594207741089' data-elem-id='1594207741089'
                     data-elem-type='shape' data-field-top-value="1" data-field-top-res-960-value="1"
                     data-field-top-res-640-value="1" data-field-top-res-480-value="1" data-field-top-res-320-value="1"
                     data-field-left-value="1" data-field-left-res-960-value="-30" data-field-left-res-640-value="1"
                     data-field-left-res-480-value="1" data-field-left-res-320-value="1" data-field-height-value="69"
                     data-field-height-res-960-value="69" data-field-height-res-640-value="69"
                     data-field-height-res-480-value="69" data-field-height-res-320-value="69"
                     data-field-width-value="1198" data-field-width-res-960-value="1020"
                     data-field-width-res-640-value="639" data-field-width-res-480-value="478"
                     data-field-width-res-320-value="318" data-field-axisy-value="top" data-field-axisx-value="left"
                     data-field-container-value="grid" data-field-topunits-value="" data-field-leftunits-value=""
                     data-field-heightunits-value="" data-field-widthunits-value="">
                    <div class='tn-atom'></div>
                </div>
            </div>
        </div>
        <script>$(document).ready(function () {
                t396_init('211441746');
            });</script><!-- /T396 --></div>
    <div id="rec210041748" class="r t-rec" style=" " data-animationappear="off" data-record-type="396"><!-- T396 -->
        <style>#rec210041748 .t396__artboard {
                height: 1500px;
            }

            #rec210041748 .t396__filter {
                height: 1500px;
            }

            #rec210041748 .t396__carrier {
                height: 1500px;
                background-position: center center;
                background-attachment: scroll;
                background-size: cover;
                background-repeat: no-repeat;
            }

            @media screen and (max-width: 1199px) {
                #rec210041748 .t396__artboard {
                    height: 1500px;
                }

                #rec210041748 .t396__filter {
                    height: 1500px;
                }

                #rec210041748 .t396__carrier {
                    height: 1500px;
                    background-attachment: scroll;
                }
            }

            @media screen and (max-width: 959px) {
                #rec210041748 .t396__artboard {
                    height: 1330px;
                }

                #rec210041748 .t396__filter {
                    height: 1330px;
                }

                #rec210041748 .t396__carrier {
                    height: 1330px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec210041748 .t396__artboard {
                    height: 1150px;
                }

                #rec210041748 .t396__filter {
                    height: 1150px;
                }

                #rec210041748 .t396__carrier {
                    height: 1150px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec210041748 .t396__artboard {
                    height: 815px;
                }

                #rec210041748 .t396__filter {
                    height: 815px;
                }

                #rec210041748 .t396__carrier {
                    height: 815px;
                }
            }

            #rec210041748 .tn-elem[data-elem-id="1594217104049"] {
                z-index: 3;
                top: 41px;
                left: calc(50% - 600px + 51px);
                width: 1088px;
                height: 1448px;
            }

            #rec210041748 .tn-elem[data-elem-id="1594217104049"] .tn-atom {
                background-color: #5d1900;
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec210041748 .tn-elem[data-elem-id="1594217104049"] {
                    top: 24px;
                    left: calc(50% - 480px + 11px);
                    width: 934px;
                    height: 1464px;
                }
            }

            @media screen and (max-width: 959px) {
                #rec210041748 .tn-elem[data-elem-id="1594217104049"] {
                    top: 11px;
                    left: calc(50% - 320px + 11px);
                    width: 622px;
                    height: 1292px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec210041748 .tn-elem[data-elem-id="1594217104049"] {
                    top: 5px;
                    left: calc(50% - 240px + 7px);
                    width: 465px;
                    height: 1106px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec210041748 .tn-elem[data-elem-id="1594217104049"] {
                    top: 5px;
                    left: calc(50% - 160px + 7px);
                    width: 307px;
                    height: 794px;
                }
            }

            #rec210041748 .tn-elem[data-elem-id="1594217404143"] {
                z-index: 1;
                top: 0px;
                left: calc(50% - 600px + 0px);
                width: 1199px;
                height: 1500px;
            }

            #rec210041748 .tn-elem[data-elem-id="1594217404143"] .tn-atom {
                background-color: #828282;
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec210041748 .tn-elem[data-elem-id="1594217404143"] {
                    top: 0px;
                    left: calc(50% - 480px + 0px);
                    width: 959px;
                    height: 1500px;
                }
            }

            @media screen and (max-width: 959px) {
                #rec210041748 .tn-elem[data-elem-id="1594217404143"] {
                    top: 0px;
                    left: calc(50% - 320px + 0px);
                    width: 638px;
                    height: 1330px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec210041748 .tn-elem[data-elem-id="1594217404143"] {
                    top: 0px;
                    left: calc(50% - 240px + 0px);
                    width: 479px;
                    height: 1150px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec210041748 .tn-elem[data-elem-id="1594217404143"] {
                    top: 0px;
                    left: calc(50% - 160px + 0px);
                    width: 319px;
                    height: 815px;
                }
            }

            #rec210041748 .tn-elem[data-elem-id="1594222623504"] {
                color: #ffffff;
                text-align: center;
                z-index: 5;
                top: 1340px;
                left: calc(50% - 600px + 460px);
                width: 250px;
                height: 55px;
            }

            #rec210041748 .tn-elem[data-elem-id="1594222623504"] .tn-atom {
                color: #ffffff;
                font-size: 14px;
                font-family: 'jopsima', Arial, sans-serif;
                line-height: 1.55;
                font-weight: 600;
                border-width: 1px;
                border-radius: 30px;
                background-color: #ff0000;
                background-position: center center;
                border-color: transparent;
                border-style: solid;
                transition: background-color 0.2s ease-in-out, color 0.2s ease-in-out, border-color 0.2s ease-in-out;
            }

            @media screen and (max-width: 1199px) {
                #rec210041748 .tn-elem[data-elem-id="1594222623504"] {
                    top: 1340px;
                    left: calc(50% - 480px + 350px);
                }
            }

            @media screen and (max-width: 959px) {
                #rec210041748 .tn-elem[data-elem-id="1594222623504"] {
                    top: 1180px;
                    left: calc(50% - 320px + 200px);
                }
            }

            @media screen and (max-width: 639px) {
                #rec210041748 .tn-elem[data-elem-id="1594222623504"] {
                    top: 300px;
                    left: calc(50% - 240px + 100px);
                }
            }

            @media screen and (max-width: 479px) {
                #rec210041748 .tn-elem[data-elem-id="1594222623504"] {
                    top: 245px;
                    left: calc(50% - 160px + 60px);
                    width: 190px;
                    height: 44px;
                }

                #rec210041748 .tn-elem[data-elem-id="1594222623504"] .tn-atom {
                    font-size: 10px;
                }
            }

            #rec210041748 .tn-elem[data-elem-id="1594307878302"] {
                color: #000000;
                z-index: 26;
                top: 90px;
                left: calc(50% - 600px + 440px);
                width: 310px;
            }

            #rec210041748 .tn-elem[data-elem-id="1594307878302"] .tn-atom {
                color: #000000;
                font-size: 35px;
                font-family: 'jopsima', Arial, sans-serif;
                line-height: 1.55;
                font-weight: 400;
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec210041748 .tn-elem[data-elem-id="1594307878302"] {
                    top: 93px;
                    left: calc(50% - 480px + 316px);
                }
            }

            @media screen and (max-width: 959px) {
                #rec210041748 .tn-elem[data-elem-id="1594307878302"] {
                    top: 73px;
                    left: calc(50% - 320px + 176px);
                }
            }

            @media screen and (max-width: 639px) {
                #rec210041748 .tn-elem[data-elem-id="1594307878302"] {
                    top: 45px;
                    left: calc(50% - 240px + 90px);
                }
            }

            @media screen and (max-width: 479px) {
                #rec210041748 .tn-elem[data-elem-id="1594307878302"] {
                    top: 40px;
                    left: calc(50% - 160px + 56px);
                    width: 210px;
                }

                #rec210041748 .tn-elem[data-elem-id="1594307878302"] .tn-atom {
                    font-size: 24px;
                }
            }

            #rec210041748 .tn-elem[data-elem-id="1594308014604"] {
                color: #000000;
                z-index: 27;
                top: 205px;
                left: calc(50% - 600px + 290px);
                width: 570px;
            }

            #rec210041748 .tn-elem[data-elem-id="1594308014604"] .tn-atom {
                color: #000000;
                font-size: 20px;
                font-family: 'jopsima', Arial, sans-serif;
                line-height: 1.55;
                font-weight: 400;
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec210041748 .tn-elem[data-elem-id="1594308014604"] {
                    top: 220px;
                    left: calc(50% - 480px + 170px);
                }
            }

            @media screen and (max-width: 959px) {
                #rec210041748 .tn-elem[data-elem-id="1594308014604"] {
                    top: 180px;
                    left: calc(50% - 320px + 60px);
                    width: 540px;
                }

                #rec210041748 .tn-elem[data-elem-id="1594308014604"] .tn-atom {
                    font-size: 19px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec210041748 .tn-elem[data-elem-id="1594308014604"] {
                    top: 165px;
                    left: calc(50% - 240px + 90px);
                    width: 380px;
                }

                #rec210041748 .tn-elem[data-elem-id="1594308014604"] .tn-atom {
                    font-size: 16px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec210041748 .tn-elem[data-elem-id="1594308014604"] {
                    top: 125px;
                    left: calc(50% - 160px + 50px);
                    width: 240px;
                }

                #rec210041748 .tn-elem[data-elem-id="1594308014604"] .tn-atom {
                    font-size: 12px;
                }
            }

            #rec210041748 .tn-elem[data-elem-id="1594212689292"] {
                z-index: 4;
                top: 47px;
                left: calc(50% - 600px + 58px);
                width: 1073px;
                height: 1435px;
            }

            #rec210041748 .tn-elem[data-elem-id="1594212689292"] .tn-atom {
                background-color: #e8e8e8;
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec210041748 .tn-elem[data-elem-id="1594212689292"] {
                    top: 31px;
                    left: calc(50% - 480px + 18px);
                    width: 918px;
                    height: 1442px;
                }
            }

            @media screen and (max-width: 959px) {
                #rec210041748 .tn-elem[data-elem-id="1594212689292"] {
                    top: 17px;
                    left: calc(50% - 320px + 18px);
                    width: 607px;
                    height: 1276px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec210041748 .tn-elem[data-elem-id="1594212689292"] {
                    top: 10px;
                    left: calc(50% - 240px + 13px);
                    width: 453px;
                    height: 1092px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec210041748 .tn-elem[data-elem-id="1594212689292"] {
                    top: 10px;
                    left: calc(50% - 160px + 13px);
                    width: 296px;
                    height: 778px;
                }
            }

            #rec210041748 .tn-elem[data-elem-id="1594388592148"] {
                z-index: 32;
                top: 835px;
                left: calc(50% - 600px + 290px);
                width: 580px;
            }

            #rec210041748 .tn-elem[data-elem-id="1594388592148"] .tn-atom {
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec210041748 .tn-elem[data-elem-id="1594388592148"] {
                    top: 840px;
                    left: calc(50% - 480px + 170px);
                }
            }

            @media screen and (max-width: 959px) {
                #rec210041748 .tn-elem[data-elem-id="1594388592148"] {
                    top: 770px;
                    left: calc(50% - 320px + 70px);
                    width: 480px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec210041748 .tn-elem[data-elem-id="1594388592148"] {
                    top: 800px;
                    left: calc(50% - 240px + 60px);
                    width: 370px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec210041748 .tn-elem[data-elem-id="1594388592148"] {
                    top: 490px;
                    left: calc(50% - 160px + 50px);
                    width: 210px;
                }
            }

            #rec210041748 .tn-elem[data-elem-id="1596194296262"] {
                color: #000000;
                text-align: center;
                z-index: 35;
                top: 775px;
                left: calc(50% - 600px + 320px);
                width: 560px;
            }

            #rec210041748 .tn-elem[data-elem-id="1596194296262"] .tn-atom {
                color: #000000;
                font-size: 10px;
                font-family: 'jopsima', Arial, sans-serif;
                line-height: 1.55;
                font-weight: 400;
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec210041748 .tn-elem[data-elem-id="1596194296262"] {
                    top: 785px;
                    left: calc(50% - 480px + 200px);
                }
            }

            @media screen and (max-width: 959px) {
                #rec210041748 .tn-elem[data-elem-id="1596194296262"] {
                    top: 695px;
                    left: calc(50% - 320px + 60px);
                    width: 530px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec210041748 .tn-elem[data-elem-id="1596194296262"] {
                    top: 695px;
                    left: calc(50% - 240px + 40px);
                    width: 400px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec210041748 .tn-elem[data-elem-id="1596194296262"] {
                    top: 680px;
                    left: calc(50% - 160px + 50px);
                    width: 220px;
                }
            }

            #rec210041748 .tn-elem[data-elem-id="1596568791185"] {
                z-index: 36;
                top: 315px;
                left: calc(50% - 600px + 290px);
                width: 580px;
            }

            #rec210041748 .tn-elem[data-elem-id="1596568791185"] .tn-atom {
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec210041748 .tn-elem[data-elem-id="1596568791185"] {
                    top: 330px;
                    left: calc(50% - 480px + 170px);
                }
            }

            @media screen and (max-width: 959px) {
                #rec210041748 .tn-elem[data-elem-id="1596568791185"] {
                    top: 285px;
                    left: calc(50% - 320px + 70px);
                    width: 480px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec210041748 .tn-elem[data-elem-id="1596568791185"] {
                    top: 390px;
                    left: calc(50% - 240px + 60px);
                    width: 370px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec210041748 .tn-elem[data-elem-id="1596568791185"] {
                    top: 315px;
                    left: calc(50% - 160px + 52px);
                    width: 210px;
                }
            }

            #rec210041748 .tn-elem[data-elem-id="1596569268367"] {
                color: #000000;
                z-index: 37;
                top: 160px;
                left: calc(50% - 600px + 290px);
                width: 570px;
            }

            #rec210041748 .tn-elem[data-elem-id="1596569268367"] .tn-atom {
                color: #000000;
                font-size: 20px;
                font-family: 'jopsima', Arial, sans-serif;
                line-height: 1.55;
                font-weight: 400;
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec210041748 .tn-elem[data-elem-id="1596569268367"] {
                    top: 178 pxpx;
                    left: calc(50% - 480px + 167pxpx);
                }
            }

            @media screen and (max-width: 959px) {
                #rec210041748 .tn-elem[data-elem-id="1596569268367"] {
                    top: 144px;
                    left: calc(50% - 320px + 60px);
                    width: 540px;
                }

                #rec210041748 .tn-elem[data-elem-id="1596569268367"] .tn-atom {
                    font-size: 19px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec210041748 .tn-elem[data-elem-id="1596569268367"] {
                    top: 125px;
                    left: calc(50% - 240px + 90px);
                    width: 380px;
                }

                #rec210041748 .tn-elem[data-elem-id="1596569268367"] .tn-atom {
                    font-size: 16px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec210041748 .tn-elem[data-elem-id="1596569268367"] {
                    top: 100 pxpx;
                    left: calc(50% - 160px + 52pxpx);
                    width: 240px;
                }

                #rec210041748 .tn-elem[data-elem-id="1596569268367"] .tn-atom {
                    font-size: 12px;
                }
            }</style>
        <div class='t396'>
            <div class="t396__artboard" data-artboard-recid="210041748" data-artboard-height="1500"
                 data-artboard-height-res-960="1500" data-artboard-height-res-640="1330"
                 data-artboard-height-res-480="1150" data-artboard-height-res-320="815" data-artboard-height_vh=""
                 data-artboard-valign="center" data-artboard-ovrflw="">
                <div class="t396__carrier" data-artboard-recid="210041748"></div>
                <div class="t396__filter" data-artboard-recid="210041748"></div>
                <div class='t396__elem tn-elem tn-elem__2100417481594217104049' data-elem-id='1594217104049'
                     data-elem-type='shape' data-field-top-value="41" data-field-top-res-960-value="24"
                     data-field-top-res-640-value="11" data-field-top-res-480-value="5" data-field-top-res-320-value="5"
                     data-field-left-value="51" data-field-left-res-960-value="11" data-field-left-res-640-value="11"
                     data-field-left-res-480-value="7" data-field-left-res-320-value="7" data-field-height-value="1448"
                     data-field-height-res-960-value="1464" data-field-height-res-640-value="1292"
                     data-field-height-res-480-value="1106" data-field-height-res-320-value="794"
                     data-field-width-value="1088" data-field-width-res-960-value="934"
                     data-field-width-res-640-value="622" data-field-width-res-480-value="465"
                     data-field-width-res-320-value="307" data-field-axisy-value="top" data-field-axisx-value="left"
                     data-field-container-value="grid" data-field-topunits-value="" data-field-leftunits-value=""
                     data-field-heightunits-value="" data-field-widthunits-value="">
                    <div class='tn-atom'></div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2100417481594217404143' data-elem-id='1594217404143'
                     data-elem-type='shape' data-field-top-value="0" data-field-top-res-960-value="0"
                     data-field-top-res-640-value="0" data-field-top-res-480-value="0" data-field-top-res-320-value="0"
                     data-field-left-value="0" data-field-left-res-960-value="0" data-field-left-res-640-value="0"
                     data-field-left-res-480-value="0" data-field-left-res-320-value="0" data-field-height-value="1500"
                     data-field-height-res-960-value="1500" data-field-height-res-640-value="1330"
                     data-field-height-res-480-value="1150" data-field-height-res-320-value="815"
                     data-field-width-value="1199" data-field-width-res-960-value="959"
                     data-field-width-res-640-value="638" data-field-width-res-480-value="479"
                     data-field-width-res-320-value="319" data-field-axisy-value="top" data-field-axisx-value="left"
                     data-field-container-value="grid" data-field-topunits-value="" data-field-leftunits-value=""
                     data-field-heightunits-value="" data-field-widthunits-value="">
                    <div class='tn-atom'></div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2100417481594222623504' data-elem-id='1594222623504'
                     data-elem-type='button' data-field-top-value="1340" data-field-top-res-960-value="1340"
                     data-field-top-res-640-value="1180" data-field-top-res-480-value="300"
                     data-field-top-res-320-value="245" data-field-left-value="460" data-field-left-res-960-value="350"
                     data-field-left-res-640-value="200" data-field-left-res-480-value="100"
                     data-field-left-res-320-value="60" data-field-height-value="55"
                     data-field-height-res-320-value="44" data-field-width-value="250"
                     data-field-width-res-320-value="190" data-field-axisy-value="top" data-field-axisx-value="left"
                     data-field-container-value="grid" data-field-topunits-value="" data-field-leftunits-value=""
                     data-field-heightunits-value="" data-field-widthunits-value="">
                    <div class='tn-atom'>Питание мегатрона отключено</div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2100417481594307878302' data-elem-id='1594307878302'
                     data-elem-type='text' data-field-top-value="90" data-field-top-res-960-value="93"
                     data-field-top-res-640-value="73" data-field-top-res-480-value="45"
                     data-field-top-res-320-value="40" data-field-left-value="440" data-field-left-res-960-value="316"
                     data-field-left-res-640-value="176" data-field-left-res-480-value="90"
                     data-field-left-res-320-value="56" data-field-width-value="310"
                     data-field-width-res-320-value="210" data-field-axisy-value="top" data-field-axisx-value="left"
                     data-field-container-value="grid" data-field-topunits-value="" data-field-leftunits-value=""
                     data-field-heightunits-value="" data-field-widthunits-value="">
                    <div class='tn-atom' field='tn_text_1594307878302'>МЕГАТРОН 3000</div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2100417481594308014604' data-elem-id='1594308014604'
                     data-elem-type='text' data-field-top-value="205" data-field-top-res-960-value="220"
                     data-field-top-res-640-value="180" data-field-top-res-480-value="165"
                     data-field-top-res-320-value="125" data-field-left-value="290" data-field-left-res-960-value="170"
                     data-field-left-res-640-value="60" data-field-left-res-480-value="90"
                     data-field-left-res-320-value="50" data-field-width-value="570"
                     data-field-width-res-640-value="540" data-field-width-res-480-value="380"
                     data-field-width-res-320-value="240" data-field-axisy-value="top" data-field-axisx-value="left"
                     data-field-container-value="grid" data-field-topunits-value="" data-field-leftunits-value=""
                     data-field-heightunits-value="" data-field-widthunits-value="">
                    <div class='tn-atom' field='tn_text_1594308014604'>Рабочая страница управления Мегатроном 3000:
                        лазерный модуль для резки и маркировки LSMVR450-3000MF 3000мВт 450нм с ручной фокусировкой. <br><br>
                    </div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2100417481594212689292' data-elem-id='1594212689292'
                     data-elem-type='shape' data-field-top-value="47" data-field-top-res-960-value="31"
                     data-field-top-res-640-value="17" data-field-top-res-480-value="10"
                     data-field-top-res-320-value="10" data-field-left-value="58" data-field-left-res-960-value="18"
                     data-field-left-res-640-value="18" data-field-left-res-480-value="13"
                     data-field-left-res-320-value="13" data-field-height-value="1435"
                     data-field-height-res-960-value="1442" data-field-height-res-640-value="1276"
                     data-field-height-res-480-value="1092" data-field-height-res-320-value="778"
                     data-field-width-value="1073" data-field-width-res-960-value="918"
                     data-field-width-res-640-value="607" data-field-width-res-480-value="453"
                     data-field-width-res-320-value="296" data-field-axisy-value="top" data-field-axisx-value="left"
                     data-field-container-value="grid" data-field-topunits-value="" data-field-leftunits-value=""
                     data-field-heightunits-value="" data-field-widthunits-value="">
                    <div class='tn-atom'></div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2100417481594388592148' data-elem-id='1594388592148'
                     data-elem-type='image' data-field-top-value="835" data-field-top-res-960-value="840"
                     data-field-top-res-640-value="770" data-field-top-res-480-value="800"
                     data-field-top-res-320-value="490" data-field-left-value="290" data-field-left-res-960-value="170"
                     data-field-left-res-640-value="70" data-field-left-res-480-value="60"
                     data-field-left-res-320-value="50" data-field-width-value="580"
                     data-field-width-res-640-value="480" data-field-width-res-480-value="370"
                     data-field-width-res-320-value="210" data-field-axisy-value="top" data-field-axisx-value="left"
                     data-field-container-value="grid" data-field-topunits-value="" data-field-leftunits-value=""
                     data-field-heightunits-value="" data-field-widthunits-value="">
                    <div class='tn-atom'><img class='tn-atom__img t-img'
                                              data-original='//ooosokol.ru/images/tild6561-3434-4565-b032-656234633535____.png'
                                              imgfield='tn_img_1594388592148'></div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2100417481596194296262' data-elem-id='1596194296262'
                     data-elem-type='text' data-field-top-value="775" data-field-top-res-960-value="785"
                     data-field-top-res-640-value="695" data-field-top-res-480-value="695"
                     data-field-top-res-320-value="680" data-field-left-value="320" data-field-left-res-960-value="200"
                     data-field-left-res-640-value="60" data-field-left-res-480-value="40"
                     data-field-left-res-320-value="50" data-field-width-value="560"
                     data-field-width-res-640-value="530" data-field-width-res-480-value="400"
                     data-field-width-res-320-value="220" data-field-axisy-value="top" data-field-axisx-value="left"
                     data-field-container-value="grid" data-field-topunits-value="" data-field-leftunits-value=""
                     data-field-heightunits-value="" data-field-widthunits-value="">
                    <div class='tn-atom' field='tn_text_1596194296262'>Пометка мне: если система подачи питания на
                        мегатрон не срабатывает,значит выбило пробку. <br>Придется звонить в управляющую компанию и
                        просить включить
                    </div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2100417481596568791185' data-elem-id='1596568791185'
                     data-elem-type='image' data-field-top-value="315" data-field-top-res-960-value="330"
                     data-field-top-res-640-value="285" data-field-top-res-480-value="390"
                     data-field-top-res-320-value="315" data-field-left-value="290" data-field-left-res-960-value="170"
                     data-field-left-res-640-value="70" data-field-left-res-480-value="60"
                     data-field-left-res-320-value="52" data-field-width-value="580"
                     data-field-width-res-640-value="480" data-field-width-res-480-value="370"
                     data-field-width-res-320-value="210" data-field-axisy-value="top" data-field-axisx-value="left"
                     data-field-container-value="grid" data-field-topunits-value="" data-field-leftunits-value=""
                     data-field-heightunits-value="" data-field-widthunits-value="">
                    <div class='tn-atom'><img class='tn-atom__img t-img'
                                              data-original='//ooosokol.ru/images/tild6638-6563-4162-b163-386538363263___.png'
                                              imgfield='tn_img_1596568791185'></div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2100417481596569268367' data-elem-id='1596569268367'
                     data-elem-type='text' data-field-top-value="160" data-field-top-res-960-value="178px"
                     data-field-top-res-640-value="144" data-field-top-res-480-value="125"
                     data-field-top-res-320-value="100px" data-field-left-value="290"
                     data-field-left-res-960-value="167px" data-field-left-res-640-value="60"
                     data-field-left-res-480-value="90" data-field-left-res-320-value="52px"
                     data-field-width-value="570" data-field-width-res-640-value="540"
                     data-field-width-res-480-value="380" data-field-width-res-320-value="240"
                     data-field-axisy-value="top" data-field-axisx-value="left" data-field-container-value="grid"
                     data-field-topunits-value="" data-field-leftunits-value="" data-field-heightunits-value=""
                     data-field-widthunits-value="">
                    <div class='tn-atom' field='tn_text_1596569268367'>Оружие на самый крайний случай.</div>
                </div>
            </div>
        </div>
        <script>$(document).ready(function () {
                t396_init('210041748');
            });</script><!-- /T396 --></div>
    <div id="rec218160543" class="r t-rec" style=" " data-animationappear="off" data-record-type="396"><!-- T396 -->
        <style>#rec218160543 .t396__artboard {
                height: 312px;
                background-color: #ffffff;
            }

            #rec218160543 .t396__filter {
                height: 312px;
            }

            #rec218160543 .t396__carrier {
                height: 312px;
                background-position: center center;
                background-attachment: scroll;
                background-size: cover;
                background-repeat: no-repeat;
            }

            @media screen and (max-width: 1199px) {
                #rec218160543 .t396__artboard {
                    height: 292px;
                }

                #rec218160543 .t396__filter {
                    height: 292px;
                }

                #rec218160543 .t396__carrier {
                    height: 292px;
                    background-attachment: scroll;
                }
            }

            @media screen and (max-width: 959px) {
                #rec218160543 .t396__artboard {
                    height: 684px;
                }

                #rec218160543 .t396__filter {
                    height: 684px;
                }

                #rec218160543 .t396__carrier {
                    height: 684px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec218160543 .t396__artboard {
                    height: 672px;
                }

                #rec218160543 .t396__filter {
                    height: 672px;
                }

                #rec218160543 .t396__carrier {
                    height: 672px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec218160543 .t396__artboard {
                    height: 660px;
                }

                #rec218160543 .t396__filter {
                    height: 660px;
                }

                #rec218160543 .t396__carrier {
                    height: 660px;
                }
            }

            #rec218160543 .tn-elem[data-elem-id="1594209623246"] {
                color: #5c4f00;
                z-index: 8;
                top: 5px;
                left: calc(50% - 600px + 130px);
                width: 110px;
            }

            #rec218160543 .tn-elem[data-elem-id="1594209623246"] .tn-atom {
                color: #5c4f00;
                font-size: 25px;
                font-family: 'jopsima', Arial, sans-serif;
                line-height: 1.55;
                font-weight: 400;
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec218160543 .tn-elem[data-elem-id="1594209623246"] {
                    top: 10px;
                    left: calc(50% - 480px + 90px);
                }
            }

            @media screen and (max-width: 959px) {
                #rec218160543 .tn-elem[data-elem-id="1594209623246"] {
                    top: 10px;
                    left: calc(50% - 320px + 260px);
                }
            }

            @media screen and (max-width: 639px) {
                #rec218160543 .tn-elem[data-elem-id="1594209623246"] {
                    top: 10px;
                    left: calc(50% - 240px + 173px);
                }
            }

            @media screen and (max-width: 479px) {
                #rec218160543 .tn-elem[data-elem-id="1594209623246"] {
                    top: 10px;
                    left: calc(50% - 160px + 110px);
                }
            }

            #rec218160543 .tn-elem[data-elem-id="1594211256667"] {
                z-index: 1;
                top: 1px;
                left: calc(50% - 600px + 0px);
                width: 1200px;
                height: 215px;
            }

            #rec218160543 .tn-elem[data-elem-id="1594211256667"] .tn-atom {
                background-color: #ff0000;
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec218160543 .tn-elem[data-elem-id="1594211256667"] {
                    top: 1px;
                    left: calc(50% - 480px + -30px);
                    width: 1021px;
                    height: 212px;
                }
            }

            @media screen and (max-width: 959px) {
                #rec218160543 .tn-elem[data-elem-id="1594211256667"] {
                    top: 0px;
                    left: calc(50% - 320px + 0px);
                    width: 638px;
                    height: 633px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec218160543 .tn-elem[data-elem-id="1594211256667"] {
                    top: 0px;
                    left: calc(50% - 240px + 0px);
                    width: 479px;
                    height: 633px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec218160543 .tn-elem[data-elem-id="1594211256667"] {
                    top: 0px;
                    left: calc(50% - 160px + 0px);
                    width: 319px;
                    height: 633px;
                }
            }

            #rec218160543 .tn-elem[data-elem-id="1594211934150"] {
                color: #5c4f00;
                z-index: 10;
                top: 45px;
                left: calc(50% - 600px + 20px);
                width: 400px;
            }

            #rec218160543 .tn-elem[data-elem-id="1594211934150"] .tn-atom {
                color: #5c4f00;
                font-size: 12px;
                font-family: 'jopsima', Arial, sans-serif;
                line-height: 1.55;
                font-weight: 400;
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec218160543 .tn-elem[data-elem-id="1594211934150"] {
                    top: 43px;
                    left: calc(50% - 480px + -14px);
                    width: 350px;
                }

                #rec218160543 .tn-elem[data-elem-id="1594211934150"] .tn-atom {
                    font-size: 10px;
                }
            }

            @media screen and (max-width: 959px) {
                #rec218160543 .tn-elem[data-elem-id="1594211934150"] {
                    top: 45px;
                    left: calc(50% - 320px + 160px);
                }
            }

            @media screen and (max-width: 639px) {
                #rec218160543 .tn-elem[data-elem-id="1594211934150"] {
                    top: 45px;
                    left: calc(50% - 240px + 82px);
                }
            }

            @media screen and (max-width: 479px) {
                #rec218160543 .tn-elem[data-elem-id="1594211934150"] {
                    top: 45px;
                    left: calc(50% - 160px + 30px);
                    width: 260px;
                }

                #rec218160543 .tn-elem[data-elem-id="1594211934150"] .tn-atom {
                    font-size: 8px;
                }
            }

            #rec218160543 .tn-elem[data-elem-id="1594211985546"] {
                color: #5c4f00;
                z-index: 11;
                top: 5px;
                left: calc(50% - 600px + 540px);
                width: 110px;
            }

            #rec218160543 .tn-elem[data-elem-id="1594211985546"] .tn-atom {
                color: #5c4f00;
                font-size: 25px;
                font-family: 'jopsima', Arial, sans-serif;
                line-height: 1.55;
                font-weight: 400;
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec218160543 .tn-elem[data-elem-id="1594211985546"] {
                    top: 10px;
                    left: calc(50% - 480px + 455px);
                }
            }

            @media screen and (max-width: 959px) {
                #rec218160543 .tn-elem[data-elem-id="1594211985546"] {
                    top: 210px;
                    left: calc(50% - 320px + 240px);
                }
            }

            @media screen and (max-width: 639px) {
                #rec218160543 .tn-elem[data-elem-id="1594211985546"] {
                    top: 210px;
                    left: calc(50% - 240px + 162px);
                }
            }

            @media screen and (max-width: 479px) {
                #rec218160543 .tn-elem[data-elem-id="1594211985546"] {
                    top: 215px;
                    left: calc(50% - 160px + 90px);
                }
            }

            #rec218160543 .tn-elem[data-elem-id="1594211999006"] {
                color: #5c4f00;
                z-index: 12;
                top: 5px;
                left: calc(50% - 600px + 850px);
                width: 110px;
            }

            #rec218160543 .tn-elem[data-elem-id="1594211999006"] .tn-atom {
                color: #5c4f00;
                font-size: 25px;
                font-family: 'jopsima', Arial, sans-serif;
                line-height: 1.55;
                font-weight: 400;
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec218160543 .tn-elem[data-elem-id="1594211999006"] {
                    top: 10px;
                    left: calc(50% - 480px + 690px);
                }
            }

            @media screen and (max-width: 959px) {
                #rec218160543 .tn-elem[data-elem-id="1594211999006"] {
                    top: 415px;
                    left: calc(50% - 320px + 170px);
                }
            }

            @media screen and (max-width: 639px) {
                #rec218160543 .tn-elem[data-elem-id="1594211999006"] {
                    top: 415px;
                    left: calc(50% - 240px + 92px);
                }
            }

            @media screen and (max-width: 479px) {
                #rec218160543 .tn-elem[data-elem-id="1594211999006"] {
                    top: 415px;
                    left: calc(50% - 160px + 20px);
                }
            }

            #rec218160543 .tn-elem[data-elem-id="1594212118215"] {
                color: #5c4f00;
                z-index: 13;
                top: 45px;
                left: calc(50% - 600px + 430px);
                width: 360px;
            }

            #rec218160543 .tn-elem[data-elem-id="1594212118215"] .tn-atom {
                color: #5c4f00;
                font-size: 12px;
                font-family: 'jopsima', Arial, sans-serif;
                line-height: 1.55;
                font-weight: 400;
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec218160543 .tn-elem[data-elem-id="1594212118215"] {
                    top: 55px;
                    left: calc(50% - 480px + 374px);
                    width: 290px;
                }

                #rec218160543 .tn-elem[data-elem-id="1594212118215"] .tn-atom {
                    font-size: 10px;
                }
            }

            @media screen and (max-width: 959px) {
                #rec218160543 .tn-elem[data-elem-id="1594212118215"] {
                    top: 255px;
                    left: calc(50% - 320px + 160px);
                }
            }

            @media screen and (max-width: 639px) {
                #rec218160543 .tn-elem[data-elem-id="1594212118215"] {
                    top: 255px;
                    left: calc(50% - 240px + 82px);
                }
            }

            @media screen and (max-width: 479px) {
                #rec218160543 .tn-elem[data-elem-id="1594212118215"] {
                    top: 260px;
                    left: calc(50% - 160px + 30px);
                    width: 250px;
                }

                #rec218160543 .tn-elem[data-elem-id="1594212118215"] .tn-atom {
                    font-size: 8px;
                }
            }

            #rec218160543 .tn-elem[data-elem-id="1594212211483"] {
                z-index: 14;
                top: 50px;
                left: calc(50% - 600px + 860px);
                width: 260px;
            }

            #rec218160543 .tn-elem[data-elem-id="1594212211483"] .tn-atom {
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec218160543 .tn-elem[data-elem-id="1594212211483"] {
                    top: 50px;
                    left: calc(50% - 480px + 701px);
                }
            }

            @media screen and (max-width: 959px) {
                #rec218160543 .tn-elem[data-elem-id="1594212211483"] {
                    top: 465px;
                    left: calc(50% - 320px + 180px);
                }
            }

            @media screen and (max-width: 639px) {
                #rec218160543 .tn-elem[data-elem-id="1594212211483"] {
                    top: 465px;
                    left: calc(50% - 240px + 102px);
                }
            }

            @media screen and (max-width: 479px) {
                #rec218160543 .tn-elem[data-elem-id="1594212211483"] {
                    top: 465px;
                    left: calc(50% - 160px + 30px);
                }
            }

            #rec218160543 .tn-elem[data-elem-id="1596460982376"] {
                z-index: 15;
                top: 215px;
                left: calc(50% - 600px + 0px);
                width: 1200px;
            }

            #rec218160543 .tn-elem[data-elem-id="1596460982376"] .tn-atom {
                background-position: center center;
                border-color: transparent;
                border-style: solid;
            }

            @media screen and (max-width: 1199px) {
                #rec218160543 .tn-elem[data-elem-id="1596460982376"] {
                    top: 213px;
                    left: calc(50% - 480px + -30px);
                    width: 1020px;
                }
            }

            @media screen and (max-width: 959px) {
                #rec218160543 .tn-elem[data-elem-id="1596460982376"] {
                    top: 633px;
                    left: calc(50% - 320px + 0px);
                    width: 640px;
                }
            }

            @media screen and (max-width: 639px) {
                #rec218160543 .tn-elem[data-elem-id="1596460982376"] {
                    top: 633px;
                    left: calc(50% - 240px + 0px);
                    width: 480px;
                }
            }

            @media screen and (max-width: 479px) {
                #rec218160543 .tn-elem[data-elem-id="1596460982376"] {
                    top: 633px;
                    left: calc(50% - 160px + 0px);
                    width: 320px;
                }
            }</style>
        <div class='t396'>
            <div class="t396__artboard" data-artboard-recid="218160543" data-artboard-height="312"
                 data-artboard-height-res-960="292" data-artboard-height-res-640="684"
                 data-artboard-height-res-480="672" data-artboard-height-res-320="660" data-artboard-height_vh=""
                 data-artboard-valign="center" data-artboard-ovrflw="">
                <div class="t396__carrier" data-artboard-recid="218160543"></div>
                <div class="t396__filter" data-artboard-recid="218160543"></div>
                <div class='t396__elem tn-elem tn-elem__2181605431594209623246' data-elem-id='1594209623246'
                     data-elem-type='text' data-field-top-value="5" data-field-top-res-960-value="10"
                     data-field-top-res-640-value="10" data-field-top-res-480-value="10"
                     data-field-top-res-320-value="10" data-field-left-value="130" data-field-left-res-960-value="90"
                     data-field-left-res-640-value="260" data-field-left-res-480-value="173"
                     data-field-left-res-320-value="110" data-field-width-value="110" data-field-axisy-value="top"
                     data-field-axisx-value="left" data-field-container-value="grid" data-field-topunits-value=""
                     data-field-leftunits-value="" data-field-heightunits-value="" data-field-widthunits-value="">
                    <div class='tn-atom' field='tn_text_1594209623246'>О НАС</div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2181605431594211256667' data-elem-id='1594211256667'
                     data-elem-type='shape' data-field-top-value="1" data-field-top-res-960-value="1"
                     data-field-top-res-640-value="0" data-field-top-res-480-value="0" data-field-top-res-320-value="0"
                     data-field-left-value="0" data-field-left-res-960-value="-30" data-field-left-res-640-value="0"
                     data-field-left-res-480-value="0" data-field-left-res-320-value="0" data-field-height-value="215"
                     data-field-height-res-960-value="212" data-field-height-res-640-value="633"
                     data-field-height-res-480-value="633" data-field-height-res-320-value="633"
                     data-field-width-value="1200" data-field-width-res-960-value="1021"
                     data-field-width-res-640-value="638" data-field-width-res-480-value="479"
                     data-field-width-res-320-value="319" data-field-axisy-value="top" data-field-axisx-value="left"
                     data-field-container-value="grid" data-field-topunits-value="" data-field-leftunits-value=""
                     data-field-heightunits-value="" data-field-widthunits-value="">
                    <div class='tn-atom'></div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2181605431594211934150' data-elem-id='1594211934150'
                     data-elem-type='text' data-field-top-value="45" data-field-top-res-960-value="43"
                     data-field-top-res-640-value="45" data-field-top-res-480-value="45"
                     data-field-top-res-320-value="45" data-field-left-value="20" data-field-left-res-960-value="-14"
                     data-field-left-res-640-value="160" data-field-left-res-480-value="82"
                     data-field-left-res-320-value="30" data-field-width-value="400"
                     data-field-width-res-960-value="350" data-field-width-res-320-value="260"
                     data-field-axisy-value="top" data-field-axisx-value="left" data-field-container-value="grid"
                     data-field-topunits-value="" data-field-leftunits-value="" data-field-heightunits-value=""
                     data-field-widthunits-value="">
                    <div class='tn-atom' field='tn_text_1594211934150'>Digital-агентство «Сокол» было основано в 2010
                        году. Наша компания создает сайты любого уровня сложности, также оказываем полный спектр услуг
                        по рекламе и поддержке проектов. Из сильных сторон - разработка сложных индивидуальных
                        интернет-магазинов с 100000+ товаров, взрывное SEO-продвижение с гарантией посещаемости, большой
                        опыт в веб-аналитике. Имеем представительства в Москве и казани, но работаем по всему миру. За
                        10 лет мы создали более 900 проектов.
                    </div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2181605431594211985546' data-elem-id='1594211985546'
                     data-elem-type='text' data-field-top-value="5" data-field-top-res-960-value="10"
                     data-field-top-res-640-value="210" data-field-top-res-480-value="210"
                     data-field-top-res-320-value="215" data-field-left-value="540" data-field-left-res-960-value="455"
                     data-field-left-res-640-value="240" data-field-left-res-480-value="162"
                     data-field-left-res-320-value="90" data-field-width-value="110" data-field-axisy-value="top"
                     data-field-axisx-value="left" data-field-container-value="grid" data-field-topunits-value=""
                     data-field-leftunits-value="" data-field-heightunits-value="" data-field-widthunits-value="">
                    <div class='tn-atom' field='tn_text_1594211985546'>НОВОСТИ</div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2181605431594211999006' data-elem-id='1594211999006'
                     data-elem-type='text' data-field-top-value="5" data-field-top-res-960-value="10"
                     data-field-top-res-640-value="415" data-field-top-res-480-value="415"
                     data-field-top-res-320-value="415" data-field-left-value="850" data-field-left-res-960-value="690"
                     data-field-left-res-640-value="170" data-field-left-res-480-value="92"
                     data-field-left-res-320-value="20" data-field-width-value="110" data-field-axisy-value="top"
                     data-field-axisx-value="left" data-field-container-value="grid" data-field-topunits-value=""
                     data-field-leftunits-value="" data-field-heightunits-value="" data-field-widthunits-value="">
                    <div class='tn-atom' field='tn_text_1594211999006'>ПРЕДСТАВИТЕЛЬСТВА</div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2181605431594212118215' data-elem-id='1594212118215'
                     data-elem-type='text' data-field-top-value="45" data-field-top-res-960-value="55"
                     data-field-top-res-640-value="255" data-field-top-res-480-value="255"
                     data-field-top-res-320-value="260" data-field-left-value="430" data-field-left-res-960-value="374"
                     data-field-left-res-640-value="160" data-field-left-res-480-value="82"
                     data-field-left-res-320-value="30" data-field-width-value="360"
                     data-field-width-res-960-value="290" data-field-width-res-320-value="250"
                     data-field-axisy-value="top" data-field-axisx-value="left" data-field-container-value="grid"
                     data-field-topunits-value="" data-field-leftunits-value="" data-field-heightunits-value=""
                     data-field-widthunits-value="">
                    <div class='tn-atom' field='tn_text_1594212118215'>Что делать когда у вас интернет-магазин с
                        дорогими, но крутыми вещами?<br>Ответ:<br>1)Увеличить посещаемость сайта из поисковых систем по
                        низкочастотным узкоспециализированным запросам;<br>2)Проследить пути посетителей на сайте, и
                        увеличить конверсии по заявкам;<br>3)Сделать брендовые страницы на сайте;<br>показать далее
                    </div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2181605431594212211483' data-elem-id='1594212211483'
                     data-elem-type='image' data-field-top-value="50" data-field-top-res-960-value="50"
                     data-field-top-res-640-value="465" data-field-top-res-480-value="465"
                     data-field-top-res-320-value="465" data-field-left-value="860" data-field-left-res-960-value="701"
                     data-field-left-res-640-value="180" data-field-left-res-480-value="102"
                     data-field-left-res-320-value="30" data-field-width-value="260" data-field-axisy-value="top"
                     data-field-axisx-value="left" data-field-container-value="grid" data-field-topunits-value=""
                     data-field-leftunits-value="" data-field-heightunits-value="" data-field-widthunits-value="">
                    <div class='tn-atom'><img class='tn-atom__img t-img'
                                              data-original='//ooosokol.ru/images/tild3165-3130-4934-b436-373036323864__png-transparent-russ.png'
                                              imgfield='tn_img_1594212211483'></div>
                </div>
                <div class='t396__elem tn-elem tn-elem__2181605431596460982376' data-elem-id='1596460982376'
                     data-elem-type='image' data-field-top-value="215" data-field-top-res-960-value="213"
                     data-field-top-res-640-value="633" data-field-top-res-480-value="633"
                     data-field-top-res-320-value="633" data-field-left-value="0" data-field-left-res-960-value="-30"
                     data-field-left-res-640-value="0" data-field-left-res-480-value="0"
                     data-field-left-res-320-value="0" data-field-width-value="1200"
                     data-field-width-res-960-value="1020" data-field-width-res-640-value="640"
                     data-field-width-res-480-value="480" data-field-width-res-320-value="320"
                     data-field-axisy-value="top" data-field-axisx-value="left" data-field-container-value="grid"
                     data-field-topunits-value="" data-field-leftunits-value="" data-field-heightunits-value=""
                     data-field-widthunits-value="">
                    <div class='tn-atom'><img class='tn-atom__img t-img'
                                              data-original='//ooosokol.ru/images/tild3231-3435-4433-b737-393332653364__bot_end.png'
                                              imgfield='tn_img_1596460982376'></div>
                </div>
            </div>
        </div>
        <script>$(document).ready(function () {
                t396_init('218160543');
            });</script><!-- /T396 --></div>
</div>
</body>
</html>